### ISSUE TITLE
Load only some vendor / package models.

### ISSUE THREAD

**Issue by davidrushton** [beyondcode/invoker-community#104]
This app would be great for a client to get access the database and models through a UI.

Our e-commerce projects include a package in vendor, so that's where most of the models are. I've tried the "Include vendor folder - Yes" option, but that fails because some other third-party packages have compatibility issues (Google 2FA Unit Tests in this case).

Would it be possible to have an option for "Include vendor folder" that you can specify a path or list of composer packages?

Thanks!

**Comment by mpociot** [comment]
Hey! 
Yeah, I thought about allowing users to toggle which composer dependencies to scan - as some sort of "advanced" option.
In the meantime, could you tell me the vendor of the package that is causing compatibility issues?
I have a blocklist that contains packages which should be ignored because they won't contain eloquent models anyway (such as symfony/*, guzzle, aws/* etc).

**Comment by davidrushton** [comment]
Thanks Marcel.

My Laravel 6.x projects seem to be okay, but the offending error on my Laravel 8.x project is:

```
Symfony\Component\ErrorHandler\Error\FatalError 

  Declaration of PragmaRX\Google2FAQRCode\Tests\Google2FATest::setUp() must be compatible with PHPUnit\Framework\TestCase::setUp(): void

  at /Users/david/Code/blanket/blanket/vendor/pragmarx/google2fa-qrcode/tests/Google2FATest.php:17
    13|     const EMAIL = 'acr+pragmarx@antoniocarlosribeiro.com';
    14| 
    15|     const OTP_URL = 'otpauth://totp/PragmaRX:acr+pragmarx@antoniocarlosribeiro.com?secret=ADUMJO5634NPDEKW&issuer=PragmaRX';
    16| 
  > 17|     public function setUp()
    18|     {
    19|         $this->google2fa = new Google2FA();
    20|     }
    21|
```

**Comment by mechelon** [comment]
This is currently not on our short-term roadmap, so I will close this for now. We might come back to this later when we plan a performance update for Invoker.
