### ISSUE TITLE
Feature Request: Cancel button when loading the ERD

### ISSUE THREAD

**Issue by princejohnsantillan** [beyondcode/invoker-community#105]
I accidentally click on it a lot of times and for large projects it takes a while to load so I end up force closing the app and reopening it. A cancel button would be best.

**Comment by MasterRO94** [comment]
Had the same issue.

**Comment by mpociot** [comment]
The ER Diagram is open source and available at: https://github.com/beyondcode/invoker-er-diagram-plugin
If possible, please re-create an issue on this repository (or PR the cancel button) :)
