### ISSUE TITLE
Error opening local project in windows

### ISSUE THREAD

**Issue by Abdullah-Hejazi** [beyondcode/invoker-community#106]
Hi,
I am trying to open a local project on Windows10, and it's sending me this error
![2](https://user-images.githubusercontent.com/46539561/107596783-9d82e100-6bcd-11eb-8492-84e887c9c924.PNG)

Note: this works fine on my production project (on linux server), but it doesn't work on my development project on windows.

------
**OS**: win32
**Invoker Version**: 2.2.0
**Laravel Version**: 8.24.0
**Local project**: true
**PHP Binary**: /usr/local/bin/php
**Route**: /home?project=remote-3SZaTTH6ed9fgEWT2hXS3t

**Error**:
```
Error: spawn /usr/local/bin/php ENOENT
```

**Comment by mpociot** [comment]
Please make sure to configure your local PHP binary in the Invoker settings.
https://beyondco.de/docs/invoker/settings#php-binary-path
