### ISSUE TITLE
Notifications not working when using base class

### ISSUE THREAD

**Issue by Iamscaredofcode** [beyondcode/invoker-community#108]
Hi

I am using a base class for notifications to share the notifications implementations (see below) and the issue is that Invoker does not show (1) a user selection field (the notifiable) and (2) it doesn't recognize the notifications channels (the sidebar shows "Via:" only)

Example:
```php

NotificationBase extends LaravelNotification
{
    public function via($notifiable)
    {
        return ...
    }

    public function toArray($notifiable)
    {
        return ...
    }

    public function broadcastType()
    {
        return ...
    }

    public function toBroadcast($notifiable)
    {
        return ...
    }
}

class OrderNotification extends NotificationBase
{
    ...
}

```

Thank you for Invoker tho! it really helps make life easier

**Comment by mpociot** [comment]
This will be fixed in the next Invoker release :)
