### ISSUE TITLE
[Feature] Support for custom folder structure

### ISSUE THREAD

**Issue by pxlrbt** [beyondcode/invoker-community#109]
------
**OS**: win32
**Invoker Version**: 2.2.0
**Laravel Version**: 7.17.1
**Local project**: unknown
**PHP Binary**: C:\tools\php74\php.exe
**Route**: /home?project=remote-hds6rbidXiVEVDd32K41j3

**Error**:
```
PHP Warning:  require_once(/var/www/vhosts/laravel/bootstrap/app.php): failed to open stream: No such file or directory in phar:///tmp/invoker.phar/invoker.php on line 8
PHP Fatal error:  require_once(): Failed opening required '/var/www/vhosts/laravel/bootstrap/app.php' (include_path='.:/usr/share/pear:/usr/share/php') in phar:///tmp/invoker.phar/invoker.php on line 8
```

Looks like Invoker cannot handle a custom folder structure as it requires "bootstrap/app.php" in the root directory?  Is it using hard coded paths for all folders? I have my business logic separated into a `core/` and `modules/` folder.

Maybe this could be solved by providing a separate entrypoint for Invoker for this kind of scenario, e.g. `invoker.php` file that bootstraps the application?

**Comment by mpociot** [comment]
Yeah, this is hardcoded right now as: 

```php
$app = require_once $projectPath . '/bootstrap/app.php';
```

The model detection itself is based on your composer autoload settings, so they should get detected no matter where you place them.

**Comment by pxlrbt** [comment]
> The model detection itself is based on your composer autoload settings, so they should get detected no matter where you place them.

You're right. I just saw the error message and haven't even noticed that Invoker connects anyway.

> Yeah, this is hardcoded right now as:

Would be great if Invoker could detect a `invoker.php` file in the root which would require the correct bootstrap file.

**Comment by MasterRO94** [comment]
I had the same problem with one of the projects. We have `admin/` `api/` and `core/` root folders. Admin and Api have their own bootstrap files and separate business logic from each other sharing Models and other staff via Core

**Comment by mpociot** [comment]
Invoker allows you to define a piece of code that gets evaluated before anything else. I think this feature can be used to customize the bootstrapping process/bootstrap additional files.

![image](https://user-images.githubusercontent.com/804684/116371063-50e19600-a80b-11eb-86c6-f7c3ee8eb1f2.png)

**Comment by pxlrbt** [comment]
@mpociot Not really sure how to use this. I tried these two:

- `$app = require_once $projectPath . '/core/bootstrap/app.php';`
- `$projectPath = $projectPath . '/core';`

But in both cases it still fails as it tries to load `/bootstrap/app.php`

**Comment by agentphoenix** [comment]
@mpociot Is there any movement on this? Running into the same issue and cannot use Invoker at all because some of my projects use a custom folder structure.

**Comment by pxlrbt** [comment]
@mpociot Can you please reopen that issue as the proposed solution doesn't work?

**Comment by agentphoenix** [comment]
Still waiting for a solution to this as most of my project use a custom folder structure and I can't use Invoker at all.

**Comment by agentphoenix** [comment]
Bumping this again. Would love to see a solution so that I can use Invoker with projects that have a custom folder structure.
