### ISSUE TITLE
[Feature Request] Easy way to enter the current date/time in date/time fields

### ISSUE THREAD

**Issue by squatto** [beyondcode/invoker-community#111]
When inserting a new record for a model, it would be very helpful to be able to easily enter the current date/time into fields like `created_at` and `updated_at`. With the way it currently works, you have to click the current date and the time defaults to noon, so you have to manually change it to the current time:

<img width="321" alt="Screen Shot 2021-02-11 at 11 01 48 AM" src="https://user-images.githubusercontent.com/748444/107678428-9d7bf300-6c58-11eb-8fd4-d08bfeef5afd.png">

<img width="318" alt="Screen Shot 2021-02-11 at 11 02 00 AM" src="https://user-images.githubusercontent.com/748444/107678436-9fde4d00-6c58-11eb-95b0-107b9415c54f.png">

Maybe "Today" and "Now" buttons at the bottom of the calendar/time picker? "Today" selects today's date and shows the time selector. "Now" selects both today's date _and_ the current time and closes the entire picker, making it a simple single click process. Date-only fields would only have the "Today" button, and time-only fields would only have the "Now" button.

Thanks!

**Comment by mechelon** [comment]
A variant of this will be added in the next version. ☺️
