### ISSUE TITLE
Empty date/time fields get a value on blur, even if you don't want them to

### ISSUE THREAD

**Issue by squatto** [beyondcode/invoker-community#112]
If you click into an empty date/time field and then click out of it, the field value becomes today at noon. The same thing happens if you tab through the fields with your keyboard. Every single empty date/time field ends up as today at noon:

![tab-through-datetime-fields](https://user-images.githubusercontent.com/748444/107679871-568efd00-6c5a-11eb-9bb4-94e01b1e62ca.gif)

**Comment by mpociot** [comment]
This will be fixed in the next release
