### ISSUE TITLE
Manually changing the date/time in the input is ignored/overwritten by the picker value

### ISSUE THREAD

**Issue by squatto** [beyondcode/invoker-community#114]
If you manually type in/change a date/time value, when the field is blurred the value is overwritten by whatever value happened to be selected in the picker.

In the video below, the field is initially set to `02/10/2021 22:05:00`. I click into the field and manually change it to `02/12/2021 12:21:00`, and then I tab out of the field and it is changed to `02/10/2021 22:05:00` (which is what the picker was set to).

<img width="300" alt="manual-datetime-change-ignored" src="https://user-images.githubusercontent.com/748444/107689461-159ce580-6c66-11eb-8ab1-5a25637839b6.gif">

You are forced to make all date/time changes in the picker, even though you _can_ type them in as well. This could be fixed by keeping the input and the picker in sync as changes are made, either as they are typed in (change the picker) or as they are selected in the picker (change the input).

Thanks!

**Comment by mpociot** [comment]
Right, you'll need to press enter at the moment to apply the changes instead of just tabbing out.
