### ISSUE TITLE
[Suggestion] Indicate that you can drag/drop visible columns to change the order

### ISSUE THREAD

**Issue by squatto** [beyondcode/invoker-community#115]
When you are changing the visible columns, it isn't clear that you can drag/drop the columns to change the order:

<img src="https://user-images.githubusercontent.com/748444/107696139-d030e600-6c6e-11eb-9a0f-4bf4f17a0c8b.png" width="300">

Maybe a simple message beneath the "VISIBLE COLUMNS" header, or an icon on each row?

I found an image [on this page](https://ux.stackexchange.com/questions/26121/what-is-a-good-visual-cue-for-drag-and-drop-for-reordering-a-list-of-items) that shows some good ideas:

<img src="https://user-images.githubusercontent.com/748444/107696490-40d80280-6c6f-11eb-853e-c813a0b95710.png" width="600">

**Comment by mpociot** [comment]
Great suggestion. This will be added in the next release.
