### ISSUE TITLE
YEAR datatype interpreted as date

### ISSUE THREAD

**Issue by io238** [beyondcode/invoker-community#117]
The MySQL datatype `YEAR` (four digits) is incorrectly interpreted as `DATE`.

This causes that all years (e.g. 1964, 1999, 2021, etc.) are parsed as 1970-01-01.

### Output

![image](https://user-images.githubusercontent.com/26689138/107754963-80abf200-6d22-11eb-862d-493dd059d0ff.png)

### Example Migration
`$table->year('year_of_birth')->nullable();`

### Reference
https://dev.mysql.com/doc/refman/5.7/en/year.html

**Comment by mpociot** [comment]
This will be fixed in the next update.
