### ISSUE TITLE
Notification toArray bug

### ISSUE THREAD

**Issue by jsandfordhughes** [beyondcode/invoker-community#118]
When trying to preview a notification we have via set to broadcast and database

`public function via($notifiable)
    {
        return ['broadcast', 'database'];
    }`

As per the docs we only have a `toArray()` method in the notification however Invoker tries to look for a `toDatabase()` and `toBroadcast()` method but fails

https://laravel.com/docs/8.x/notifications#todatabase-vs-toarray

**Comment by mpociot** [comment]
This will be fixed in the next release
