### ISSUE TITLE
  Interface 'Illuminate\Contracts\Logging\Log' not found (bugsnag-laravel)

### ISSUE THREAD

**Issue by eduardocruz** [beyondcode/invoker-community#119]
Seems like an issue with the bugsnag-laravel package.

It seems like as a result, not all models are loaded by Invoker. It loads 21 out of 27 models.

reference: https://github.com/bugsnag/bugsnag-laravel/issues/286

------
**OS**: darwin
**Invoker Version**: 2.2.0
**Laravel Version**: 8.27.0
**Local project**: true
**PHP Binary**: /usr/local/bin/php
**Route**: /project/placeholder?project=local-5W1erA9d74oSHsgxAwPbee

**Error**:
```
Error 

  Interface 'Illuminate\Contracts\Logging\Log' not found

  at /Code/myproject/vendor/bugsnag/bugsnag-laravel/src/LaravelLogger.php:12
      8▕ use Illuminate\Contracts\Logging\Log;
      9▕ use Illuminate\Contracts\Support\Arrayable;
     10▕ use Illuminate\Contracts\Support\Jsonable;
     11▕ 
  ➜  12▕ class LaravelLogger extends BugsnagLogger implements Log
     13▕ {
     14▕     use EventTrait;
     15▕ 
     16▕     /**

      [2m+2 vendor frames [22m
  3   [internal]:0
      Composer\Autoload\ClassLoader::loadClass("Bugsnag\BugsnagLaravel\LaravelLogger")

  4   [internal]:0
      spl_autoload_call("Bugsnag\BugsnagLaravel\LaravelLogger")
```

**Comment by mpociot** [comment]
Thanks for reporting this. It's weird that this affects some models though.
Could you give me an example of a missing model? Doe sit have any reference to the Bugsnag package?

**Comment by mpociot** [comment]
I'll close this due to inactivity. Feel free to reopen this.
