### ISSUE TITLE
The default php path is invalid on windows

### ISSUE THREAD

**Issue by stubbo** [beyondcode/invoker-community#12]
First time starting the application the default php path is `/usr/local/bin/php`

**Comment by williamengbjerg** [comment]
Same here (Mac Mini M1). Using Docker.. hmm.
            
------
**OS**: darwin
**Invoker Version**: 2.0.1
**PHP Binary**: /usr/local/bin/php
**Route**: /home?project=local-epdJW4Bups8DMfE9Hmd78E

**Error**:
```
Error: spawn /usr/local/bin/php ENOENT
```

**Comment by sschlein** [comment]
You can change it here:

https://beyondco.de/docs/invoker/settings

We'll enhance the docs later today and will provide an update for the app in the next days. As long as it can be solved by changing the settings manually, we keep collecting error for a day or 2 before we deploy first fixes.
