### ISSUE TITLE
TelescopeServiceProvider error on production environments

### ISSUE THREAD

**Issue by voicecode-bv** [beyondcode/invoker-community#121]
When opening a project (production environment) where Telescope is installed for dev environments only, there's an error thrown. Is there some way to mute this?
           
------
**OS**: darwin
**Invoker Version**: 2.2.0
**Laravel Version**: 8.27.0
**Local project**: unknown
**PHP Binary**: /usr/local/bin/php
**Route**: /project/placeholder?project=remote-9xb6FqdSaT5DwY4saPrues

**Error**:
```
In TelescopeServiceProvider.php line 10:
                                                                           
  Class "Laravel\Telescope\TelescopeApplicationServiceProvider" not found
```

**Comment by mpociot** [comment]
Do you still get a list of all models/mails/etc? So it's just the error that should be muted?

**Comment by voicecode-bv** [comment]
@mpociot Thanks for pointing that out. No I only see Models.

**Comment by mpociot** [comment]
Should you see notifications/mails? 😅 
I'm not entirely sure if this is just a nagging popup, or if it's something that adds a bug into Invoker.

**Comment by mpociot** [comment]
If this error persists and you are sure that notifications and mails are invisible because of this, feel free to reopen this.
