### ISSUE TITLE
Fresh Laravel install error, same error I've gotten on every folder attempted prior. Not sure what is causing it? 

### ISSUE THREAD

**Issue by fairhopeweb** [beyondcode/invoker-community#123]
------
**OS**: win32
**Invoker Version**: 2.2.0
**Laravel Version**: unknown
**Local project**: true
**PHP Binary**: /usr/local/bin/php
**Route**: /home

**Error**:
```
Error: spawn /usr/local/bin/php ENOENT
```

**Comment by mpociot** [comment]
Please change your PHP binary in the Invoker settings 👍
