### ISSUE TITLE
Cannot install Enlightn Plugin on Windows.

### ISSUE THREAD

**Issue by JackGamesFTW** [beyondcode/invoker-community#124]
When trying to install the Enlightn plugin on Windows I get a error.

I also tried to run invoker as admin then install it but it did not help.

![image](https://user-images.githubusercontent.com/28160910/107983689-39419200-6fbe-11eb-9c7e-f88c5fac31e4.png)

**Comment by mpociot** [comment]
Does this only happen with the Enlightn plugin for you? Or also for other plugins?

**Comment by JackGamesFTW** [comment]
Only the Enlightn Plugin. A friend also has the same issue aswell and cannot install the plugin.

**Comment by stubbo** [comment]
I have managed to install it manually by copying to files - it now work locally but not over ssh

**Comment by mpociot** [comment]
This will be fixed in the next version of Invoker.
