### ISSUE TITLE
Support interactive Artisan commands (ask(), choice())

### ISSUE THREAD

**Issue by woganmay** [beyondcode/invoker-community#126]
I got a copy of Invoker last night and I can immediately see where it's going to be super useful for our support team. The *one* thing it doesn't seem to handle though, are interactive Artisan commands.

I'm not sure whether it's possible to introduce support for it, but if we were able to run through interactive commands wizard-style in the app, it would make it immediately useful. Is that a possibility?

**Comment by mpociot** [comment]
I'll close this in favor of #62
