### ISSUE TITLE
Not all models load

### ISSUE THREAD

**Issue by eduardocruz** [beyondcode/invoker-community#129]
I realized that a couple of my models didn't load locally. I tried just removing all the methods and they did load. That said, I'm assuming some kind of inconsistency is happening that is avoiding the model to load. On the other hand, if a file is a model, but Invoker did not load for whatever reason, would be nice to receive an error message about that. "Model not loaded" error, or whatever. 

OS: darwin
Invoker Version: 2.2.0
Laravel Version: 8.27.0
Local project: true
PHP Binary: /usr/local/bin/php

**Comment by mpociot** [comment]
Mhm yeah, I'll try to add some kind of verbose/debug mode in there. 
I suppose there was/is an issue when Invoker is evaluating the model code.

**Comment by MasterRO94** [comment]
Hi @mpociot 
I found new isssue preventing Model loading.
I've upgraded PHP to version 8 and created a new model mutator with a union type parameter. Removing typhint or use any of `Amount/float` brings the model back.

<img width="862" alt="muator-union" src="https://user-images.githubusercontent.com/7365389/110185197-65f90480-7e1a-11eb-8c0e-3df61242fd76.png">

**Comment by mpociot** [comment]
@MasterRO94 Did you change your PHP interpreter in Invoker as well?

**Comment by MasterRO94** [comment]
@mpociot 
Sure, Invoker throws an error on launch if don't  change the PHP interpreter

**Comment by mpociot** [comment]
@MasterRO94 I'm unable to reproduce this issue locally. Could you maybe provide an example github repository?
When I add a mutator that uses union types, it works for me.

**Comment by MasterRO94** [comment]
@mpociot I could not reproduce the issue on fresh laravel installation only in my project. So it would be cool to have some kind of logs to see the reason why Invoker cannot load the model.

https://user-images.githubusercontent.com/7365389/116418461-d59cd600-a844-11eb-99dd-bca82ad63f6a.mp4

**Comment by mpociot** [comment]
@MasterRO94 Please take a look at `~/Library/Logs/Invoker/renderer.log`
There you see all invoker calls, arguments, and their responses.

**Comment by mechelon** [comment]
I will close this issue due to inactivity.

If this issue still exists, feel free to reopen and, if applicable, provide more details.
