### ISSUE TITLE
[Feature Request] Invoke void model methods

### ISSUE THREAD

**Issue by woganmay** [beyondcode/invoker-community#130]
This one would be super useful for us, since it would give us access to these events without having to write any code in Tinkerwell: For any model method that has a void return, and only requires simple parameters, the ability to invoke that with a click (same UX as the Artisan Command runner).

Via Tinker, we'd typically do this with `$instance = Model::find(id); $instance->method()`, for basic methods like this:

![image](https://user-images.githubusercontent.com/225550/108214154-8184bf80-7138-11eb-97e5-a9d0f8454f76.png)

**Comment by mpociot** [comment]
Yeah, I can see this being useful - I'm not entirely sure if this should be in the app, or if it's more of a plugin use-case.

**Comment by woganmay** [comment]
I'd actually be quite happy to start working on a plugin for this (mostly just to figure out how to do that), but right now I'm blocked :( 

![Screenshot 2021-02-26 at 09 41 01](https://user-images.githubusercontent.com/225550/109270532-d4d0cf00-7816-11eb-8682-2877f71c395f.png)

**Comment by mpociot** [comment]
@woganmay Right - at the moment you need to create a plugin inside of a project and can't create a project without being in a project scope. I'll fix this!
