### ISSUE TITLE
Not all accessors available

### ISSUE THREAD

**Issue by MasterRO94** [beyondcode/invoker-community#131]
I couldn't find one model accessor and then mentioned only 5 of 13 accessors are available.

![image](https://user-images.githubusercontent.com/7365389/108274863-25dd2500-717e-11eb-928b-803c850b2a85.png)
![image](https://user-images.githubusercontent.com/7365389/108274870-28d81580-717e-11eb-8a16-27d9ddfb7aa9.png)

            
------
**OS**: darwin
**Invoker Version**: 2.2.0
**Laravel Version**: 8.26.1
**Local project**: true
**PHP Binary**: /usr/local/bin/php
**Route**: /mails/details?class=App%5CMail%5CAdmin%5CCustomerCancelledBookingAdminMail&project=local-m8EwF19fLVB9BGd6it2eHc

**Comment by mpociot** [comment]
Could you show a code snippet of one of the missing accessors?

**Comment by MasterRO94** [comment]
@mpociot 
Sure
![image](https://user-images.githubusercontent.com/7365389/108362519-84e17f00-71fc-11eb-9754-edef78c3b421.png)

**Comment by mpociot** [comment]
Do you have `booking_time` and `booking_date` as columns in your database? 
Invoker only marks the accessors as `accessors` if they are not present as a regular column.

As I can see on your screenshot, the `booking_date` is displayed using your custom accessor:

![image](https://user-images.githubusercontent.com/804684/109128308-a76d1e00-774f-11eb-8a4d-155e7e3a2b8b.png)

**Comment by MasterRO94** [comment]
@mpociot 
Thanks, `booking_date` is present as a column. 
However, `number` is not present id db as a column and does not available as an accessor.

**Comment by mpociot** [comment]
Did you add the accessor later on and need to refresh the model definition in Invoker for it to show up?

Does changing the accessor method content fix this for you? I don't see why this accessor shouldn't be visible 🤔

**Comment by MasterRO94** [comment]
@mpociot 
I played with accessor content and found issue with following line `$this->provider->company` 
I don't know how to fix this.
The accessor is valid for laravel.
![Tinkerwell - doocleen 2021-03-06 01-11-03](https://user-images.githubusercontent.com/7365389/110184503-1403af00-7e19-11eb-9b32-13cbbd2dbae7.png)

<img width="744" alt="get-number-attribute" src="https://user-images.githubusercontent.com/7365389/110183826-6bede600-7e18-11eb-9102-d45cb19c5f4e.png">
<img width="520" alt="provider-relation" src="https://user-images.githubusercontent.com/7365389/110183937-9dff4800-7e18-11eb-85ed-128eeff3eb3a.png">


![255a6a6cc7fc77c6c73c86c4e8dc6429b5a21215](https://user-images.githubusercontent.com/7365389/110183611-ea965380-7e17-11eb-8dd8-7cbeae00e604.gif)

**Comment by mpociot** [comment]
This will be fixed in the next version
