### ISSUE TITLE
[Bug] Large JSON records result in broken/over-extended UI.

### ISSUE THREAD

**Issue by corsair** [beyondcode/invoker-community#132]
### Description
When clicking on the "JSON" tag element within a column designated as JSON, if the value is large enough, it will result in a large popup window that will extend past the app's UI.

In a worst-case scenario, the entire sidebar + other Invoker app elements disappear and all that is shown is the popup.

### Example
![image](https://user-images.githubusercontent.com/1847891/108365914-9dc24400-71ac-11eb-93bf-e518067b0a53.png)

### Proposed Solution
Possibly apply a max-height to these windows and/or otherwise allow for scrolling if they extend past the normal constraints.

**Comment by mpociot** [comment]
Does it even make sense to allow seeing the complete JSON in case it's really too big? Maybe this should be truncated and if you want to see all of it, you can just go to the model detail page.

**Comment by corsair** [comment]
@mpociot I think that would be a great way of handling such.
