### ISSUE TITLE
[UI/UX] Align Install Buttons on Plugin Marketplace

### ISSUE THREAD

**Issue by corsair** [beyondcode/invoker-community#133]
### Description
All of the plugin "boxes" are designed to match each other's height, however, due to differing description lengths, the Install/Installed button is not aligned with each other.

### Example
![image](https://user-images.githubusercontent.com/1847891/108367015-d9114280-71ad-11eb-913c-2e97e7426e3b.png)

### Proposed Solution
Add the classes ``flex flex-col`` to each ``group`` element, and then apply a ``margin-bottom: auto`` to the content area.

![image](https://user-images.githubusercontent.com/1847891/108367670-8b490a00-71ae-11eb-9248-59768294c59e.png)

**Comment by mpociot** [comment]
This will also be in the next update. Thank you for taking the time to report this - especially for taking the time to even provide Tailwind classes to apply ❤️
