### ISSUE TITLE
[UI/UX] Align Plugin Title and Delete Icon

### ISSUE THREAD

**Issue by corsair** [beyondcode/invoker-community#134]
### Description
The title of a plugin and its associated delete icon (trashcan) are not currently aligned.

### Example
![image](https://user-images.githubusercontent.com/1847891/108368390-3bb70e00-71af-11eb-90bd-3f35807d8b20.png)

### Proposed Solution
Apply ``items-center`` to the individual plugin header area so that these elements are aligned.

![image](https://user-images.githubusercontent.com/1847891/108368649-8b95d500-71af-11eb-8fea-4a97cfad3128.png)

**Comment by sschlein** [comment]
@corsair Man, I absolutely dislike all the issues that you create here!

They are the bare truth and since you opened them, I can't unsee these issues in the app 😂

Thanks and keep them coming!

**Comment by corsair** [comment]
> @corsair Man, I absolutely dislike all the issues that you create here!
> 
> They are the bare truth and since you opened them, I can't unsee these issues in the app 😂
> 
> Thanks and keep them coming! ❤️

I notice UI flaws faster than the DOM can render them. ;) Jokes aside, appreciate that. I live for good UI/UX.

**Comment by mpociot** [comment]
This will find its way into the next release, thanks! :)
