### ISSUE TITLE
Some events are missing from the list

### ISSUE THREAD

**Issue by MasterRO94** [beyondcode/invoker-community#137]
Some events are missing from the list and all of them are child classes of abstract `BookingEvent`. Child classes are empty.

![Invoker – doocleen (:Users:masterro:Sites:doocleen) 2021-02-19 00-21-46](https://user-images.githubusercontent.com/7365389/108429492-bc761880-7248-11eb-9780-f42ff11f9234.png)

Abstract class
<img width="718" alt="abstract-booking" src="https://user-images.githubusercontent.com/7365389/108429925-4920d680-7249-11eb-9caa-1bd8ee5a362a.png">

One of the missing
<img width="538" alt="booking-created" src="https://user-images.githubusercontent.com/7365389/108429962-53db6b80-7249-11eb-86c9-6cd4cb7edd5b.png">

------
**OS**: darwin
**Invoker Version**: 2.3.0
**Laravel Version**: 8.26.1
**Local project**: true
**PHP Binary**: /usr/local/bin/php

**Comment by mpociot** [comment]
Thank you for reporting this. The next version of Invoker will not only check the actual class, but also parent classes for their traits to detect events and jobs.
