### ISSUE TITLE
Notification doesn't work without constructor with at least one parameter

### ISSUE THREAD

**Issue by MasterRO94** [beyondcode/invoker-community#138]
If Notification doesn't have a constructor with at least one parameter invoker will not load Notifiable dropdown.

![invoker notification w-o params 2021-02-19 02-16-29](https://user-images.githubusercontent.com/7365389/108439074-429a5b00-7259-11eb-9b99-9ac14a4b1f51.gif)

**Comment by mpociot** [comment]
Thanks for reporting this. This will be fixed in the next update.
