### ISSUE TITLE
Error when Telescope is in require-dev only

### ISSUE THREAD

**Issue by ziming** [beyondcode/invoker-community#140]
This happens when I try to connect to my production laravel app. Telescope is in require-dev

------
**OS**: darwin
**Invoker Version**: 2.0.2
**Laravel Version**: 8.28.1
**PHP Binary**: /usr/local/bin/php

**Error**:
```
In TelescopeServiceProvider.php line 10:
                                                                           
  Class 'Laravel\Telescope\TelescopeApplicationServiceProvider' not found
```

**Comment by voicecode-bv** [comment]
Duplicate of #121

**Comment by mpociot** [comment]
Closing this in favor of #121
