### ISSUE TITLE
enlightn  Invalid argument supplied for foreach()

### ISSUE THREAD

**Issue by labomatik** [beyondcode/invoker-community#141]
When i try to execute the enlightn plugin i've this error:
     
------
**OS**: darwin
**Invoker Version**: 2.3.0
**Laravel Version**: 8.28.1
**Local project**: true
**PHP Binary**: /usr/local/bin/php
**Route**: /enlightn?project=local-7aNKzyE9sDuco2y4mswqdA

**Error**:
```
In index.php line 22:
                                           
  Invalid argument supplied for foreach()  
                                           

enlightn <path>
```

**Comment by mpociot** [comment]
Yeah, this seems to happen when Enlightn is unable to work with your Laravel project. I'll open source the Enlightn plugin and move the issue to the plugin.
