### ISSUE TITLE
[Feature Request] Ability to load and save Tinkerwell scripts from within Invoker UI

### ISSUE THREAD

**Issue by JonathanAspeling** [beyondcode/invoker-community#142]
Hoping I didn't overlook it - but couldn't find a way outside of copy pasting code to load tinkerwell scripts. 

Would be awesome if it could be added if not all ready.

**Comment by mpociot** [comment]
I think this is outside the scope of the Tinkerwell plugin. If you want to have the "full" Tinkerwell experience, use Tinkerwell :)

**Comment by JonathanAspeling** [comment]
100% I am doing so now! Love the latest updates <3 keep them coming! :D
