### ISSUE TITLE
Column not shown: uuid

### ISSUE THREAD

**Issue by jeroenvanrensen** [beyondcode/invoker-community#146]
Hi everyone,

I'm using Invoker, but it does not show my `uuid` column in my database.

For example in my `users` table.

## PHPmyAdmin

![afbeelding](https://user-images.githubusercontent.com/46967616/109054899-bebff300-76de-11eb-8d00-62e42db06b8d.png)

## Invoker

![afbeelding](https://user-images.githubusercontent.com/46967616/109054935-d13a2c80-76de-11eb-9a9b-a414c39b5c38.png)

It would be nice if this get's fixed.

Thank you! Jeroen

**Comment by mpociot** [comment]
Hi Jeroen,

Did you manually add the column after loading Invoker? Maybe all you need to do is refresh the model definitions: https://beyondco.de/docs/invoker/models/refresh-definition

**Comment by jeroenvanrensen** [comment]
Yes it works!
