### ISSUE TITLE
FEATURE: Connecting labeling 

### ISSUE THREAD

**Issue by mikeerickson** [beyondcode/invoker-community#148]
Is there any type of “labeling” so that I can more easily identify which connection I am working with (it only appears in the window title). I have to connect to 3 different servers (development, staging and production) the last two of which are Forge connections.

Perhaps providing the ability to set a background color for each connection, or next to the table name

Companies <label>  ←- smaller font size for label so it is not so dominant

**Comment by mechelon** [comment]
We added the IP and the label of the current connection to the footer in one of the last releases:

![CleanShot 2021-05-10 at 11 32 19@2x](https://user-images.githubusercontent.com/26432041/117638748-76638d80-b183-11eb-9f1d-48e68c3ee5b7.png)

**Comment by mikeerickson** [comment]
Thank you, I will have a look when the new version is released.
