### ISSUE TITLE
FEATURE: Tabbed model view, retain current page

### ISSUE THREAD

**Issue by mikeerickson** [beyondcode/invoker-community#149]
It would be quite nice to have a tabbed interface so i can easily view multiple models, without having to always reload the data.  If I use the "Model" view to move between models, it does a full table reload each time I select a model.

Perhaps a tabbed interface for desired models I am view **and** retain the current page as opposed to do a full reload each time. If I want to toggle between a few models to compare data, a complete reload is "painful"

**Comment by mpociot** [comment]
Did you notice that you can press CMD+T to add/open new tabs within Invoker's model view?
Isn't that what you want/need?

![image](https://user-images.githubusercontent.com/804684/109177753-6d6c3e00-7788-11eb-9543-9863a9a0bdbe.png)

**Comment by mikeerickson** [comment]
@mpociot Embarrased here, but that is exactly what I was looking for :-)

Not sure how I missed that one, but thanks!
