### ISSUE TITLE
Make the password & passphrase field hidden

### ISSUE THREAD

**Issue by JackGamesFTW** [beyondcode/invoker-community#15]
Currently when setting up an SSH Connection the password & passphrase field is shown.

I think it would be better if the fields were set to a password and then a button also added so you can hide and view the values.

I also think that the Forge API Key in preferences should be like this.

**Comment by mpociot** [comment]
I changed the password field to have a little "eye" icon that you can toggle - I'll see how we can add this for textareas in a later update.

![image](https://user-images.githubusercontent.com/804684/106753083-77889a00-662b-11eb-81de-e86b0dacc23e.png)
