### ISSUE TITLE
Anything that can be done to support MongoDB models?

### ISSUE THREAD

**Issue by kcalliauw** [beyondcode/invoker-community#158]
Edit: further clarification: 
This is not a bug report, but a feature request.

It would be great if schema-less models like with MongoDB could be explored under the "Models" section. Since MongoDB is essentially a JSON format, a simple flat listing in pages with open/collapse functionality would already be great
The same goes for many other schema-less datastores, like ElasticSearch.
To give you an idea on how to "visualize" this, you could have a look at Kibana. It just opens the root of the JSON and lets users see the properties. On hover over a property the user can select to display the property as a column for the given query. Let me know if you need screenshots of this.
For filtering, manually editing the query could be a possibility. The library I am using here extends the Eloquent Model class, so should be otherwise fully compatible with the Laravel API.

This all being said, I would understand if you consider this out of scope

------
**OS**: linux
**Invoker Version**: 2.4.0
**Laravel Version**: 8.30.0
**Local project**: unknown
**PHP Binary**: /usr/bin/php8.0
**Route**: /project/index?class=App%5CModels%5CProfile&time=1615106240424&project=remote-5xXuqTgaLqVsVzMkickwFp

**Error**:
```
TypeError 

  call_user_func_array(): Argument #1 ($callback) must be a valid callback, class MongoDB\Database does not have a method "getDoctrineDriver"

  at /var/www/html/vendor/jenssegers/mongodb/src/Jenssegers/Mongodb/Connection.php:278
    274▕      * @return mixed
    275▕      */
    276▕     public function __call($method, $parameters)
    277▕     {
  ➜ 278▕         return call_user_func_array([$this->db, $method], $parameters);
    279▕     }
    280▕ }
    281▕

      [2m+3 vendor frames [22m
  4   phar:///tmp/invoker.phar/src/Factories/AttributeCollection.php:25
      Illuminate\Database\Connection::getDoctrineSchemaManager()

  5   phar:///tmp/invoker.phar/src/Factories/AttributeCollection.php:15
      _HumbugBoxb27e6153cb07\Invoker\Factories\AttributeCollection::getColumns()
```

**Comment by mpociot** [comment]
Thanks for reporting this. Right now MongoDB support is not on our roadmap, as this might be too specific to implement.
We might come back to this at a later point though.
