### ISSUE TITLE
Several console errors after connecting via SSH to local (Homestead) project - undefined model, mutators

### ISSUE THREAD

**Issue by mdcass** [beyondcode/invoker-community#163]
------
**OS**: Catalina 10.15.7
**Invoker Version**: 2.4.0
**Laravel Version**: 7.5.2
**Local project**: via Homestead
**PHP Binary**: /usr/local/bin/php
**Route**: /project/index?class=App%5CUser&time=1615280175880&project=remote-cBEvYbfGujyTtABzomM14L

**Error**:

Console errors when connecting to local project via SSH and Homestead

![image](https://user-images.githubusercontent.com/13783325/110446380-0408fb00-80b7-11eb-9061-83f710a1270a.png)
![image](https://user-images.githubusercontent.com/13783325/110446421-0ec39000-80b7-11eb-809b-ba62b8849f69.png)

Under the models object, only 7 of many models are listed (not sure if this is just a limitation of the console). I can select a model not listed here in the left hand sidebar and will show some records.
![image](https://user-images.githubusercontent.com/13783325/110446615-4b8f8700-80b7-11eb-8243-c9d67d219fa0.png)

**Other possibly related errors**

Selecting the `User` model causes an error
![image](https://user-images.githubusercontent.com/13783325/110448560-33b90280-80b9-11eb-9f22-aa3af2c4959d.png)
Selecting a polymorphic relation from list view of a model causes an error
![image](https://user-images.githubusercontent.com/13783325/110448735-5cd99300-80b9-11eb-94e0-7d973f6935bf.png)

**Comment by mpociot** [comment]
Could you tell me the PHP version that you are using within Homestead?
It looks like Invoker is unable to execute some of the commands via SSH as the first screenshot showed a "No response from server" error.

So you are able to use Invoker, but only on certain models and not all of them?

**Comment by mdcass** [comment]
Of course, the Homestead PHP version is 7.4.10

Is there any way for me to debug any of the relevant SSH commands to try to help?

Correct, some models work, some don't - it's difficult to identify what attributes are shared between those which don't work howver you can see the output of the console for the User model in a previous screenshot - but it sounds like diving in to some of those SSH commands are the first port of call?

Happy to assist in any way I can.

**Comment by mpociot** [comment]
Thanks for the fast response. 
Can you connect via SSH to Homestead and run this command:

```
 php /tmp/invoker.phar /home/vagrant/code/hammock-app get-model-definition --model=\\App\\Models\\User
```

I'm not 100% sure if you're using the `App\Models` namespace, so you might need to adjust the command.

Sometimes SSH errors are not properly being passed to Invoker, so hopefully, this will give some detailed error information.

**Comment by mdcass** [comment]
Seems like memory issues;

`mmap() failed: [12] Cannot allocate memory`

Tried with `-d memory_limit=-1` but no joy. Will keep digging, evidently environment based, but even on my local machine (not Homestead) it's having the same issue - guessing could point to a code issue as much as anything else

**Comment by mpociot** [comment]
I'll close this as it seems to be related to your codebase, especially if increasing the memory limit doesn't help either.
