### ISSUE TITLE
BelongsToMany Relationship

### ISSUE THREAD

**Issue by phppirate** [beyondcode/invoker-community#166]
Is it possible to have a table in the model details to show BelongsToMany relationships? or Polymorphic Relationship?

I have looked around in the interface and have not found anywhere to show these. I found the relationship count column but nowhere to show the actual connected data.

**Comment by mpociot** [comment]
When you open a detail page, you can see a button called "Panels". This will hold information about all the available relations in your app:

![image](https://user-images.githubusercontent.com/804684/111152388-f230c780-8590-11eb-9827-46886fe85a79.png)

This will then be displayed as a table on the model detail view:

![image](https://user-images.githubusercontent.com/804684/111152424-fc52c600-8590-11eb-9885-fb7880f2dea1.png)
