### ISSUE TITLE
Enlightn works on local but not on prod.

### ISSUE THREAD

**Issue by Batsirai** [beyondcode/invoker-community#167]
------
**OS**: darwin
**Invoker Version**: 2.4.0
**Laravel Version**: 7.22.4
**Local project**: unknown
**PHP Binary**: /usr/local/bin/php
**Route**: /enlightn?project=remote-6KdR2VFTtt5LjRjWUTPPdR

**Error**:
```
In index.php line 22:
                                           
  Invalid argument supplied for foreach()  
                                           

enlightn <path>
```

**Comment by mpociot** [comment]
Yeah this is an issue with Enlightn itself. I'll open source the project so that this can hopefully be fixed with the help of the Enlightn devs.
