### ISSUE TITLE
Call to a member function setAppends() on null

### ISSUE THREAD

**Issue by stancl** [beyondcode/invoker-community#172]
This is happening when I'm using Invoker with @ryangjchandler's Orbit package. It seems like there should just be a check if `$this->entry` is defined, because everything is working perfectly, aside from the error message.

------
**OS**: darwin
**Invoker Version**: 2.4.0
**Laravel Version**: 8.35.1
**Local project**: true
**PHP Binary**: /usr/local/bin/php
**Route**: /project/index?class=App%5CModels%5CThread&time=1617210303470&project=local-sr1DWN82RwKKytcBba6R9x

**Error**:
```
Error 

  Call to a member function setAppends() on null

  at phar:/Applications/Invoker.app/Contents/Resources/invoker.phar/src/Actions/ShowResourceAction.php:73
     69▕     }
     70▕     public function addAccessors() : self
     71▕     {
     72▕         if (!isset($this->request->accessors) || !\count($this->request->accessors)) {
  ➜  73▕             $this->entry->setAppends([]);
     74▕             return $this;
     75▕         }
     76▕         $this->entry->setAppends($this->request->accessors);
     77▕         return $this;

  1   phar:/Applications/Invoker.app/Contents/Resources/invoker.phar/src/Actions/ShowResourceAction.php:24
      _HumbugBoxb27e6153cb07\Invoker\Actions\ShowResourceAction::addAccessors()

  2   phar:/Applications/Invoker.app/Contents/Resources/invoker.phar/src/ActionInvoker.php:33
      _HumbugBoxb27e6153cb07\Invoker\Actions\ShowResourceAction::execute()
```

**Comment by bcorcoran** [comment]
I'm also getting this error when I try to load a related model, but in my case it simply does not load a bunch of the information in the model. I'm not sure why, because viewing the same model normally (not via a relationship) lets me view it completely fine.

**Comment by mpociot** [comment]
@bcorcoran Does this also happen for you in combination with Orbit?

**Comment by bcorcoran** [comment]
> @bcorcoran Does this also happen for you in combination with Orbit?

Forgive me, what is Orbit?

**Comment by mpociot** [comment]
This will be fixed in the next release
