### ISSUE TITLE
Auth based model scopes

### ISSUE THREAD

**Issue by lefrancois** [beyondcode/invoker-community#173]
Hey there,

is there anything planed to support auth based model scopes?
In this case the jetstream currentTeam is used, which (of course) fails while opening the model if no user is set.
How about to have user credentials in the project settings which will be automatically applied?

Best,
Michael
            
------
**OS**: darwin
**Invoker Version**: 2.4.0
**Laravel Version**: 8.35.1
**Local project**: true
**PHP Binary**: /usr/local/bin/php
**Route**: /project/index?class=App%5CModels%5CTicket&time=1617219266161&project=local-3PDNTt1GTgwRjyzxSg2otY

**Error**:
```
ErrorException 

  Trying to get property 'currentTeam' of non-object

  at /Users/michaellefrancois/www/****/app/Scopes/TeamScope.php:21
     17▕      * @return void
     18▕      */
     19▕     public function apply(Builder $builder, Model $model)
     20▕     {
  ➜  21▕         $builder->where('team_id', Auth::user()->currentTeam->id);
     22▕     }
     23▕ }
     24▕

  1   /Users/michaellefrancois/www/****/app/Scopes/TeamScope.php:21
      Illuminate\Foundation\Bootstrap\HandleExceptions::handleError("Trying to get property 'currentTeam' of non-object", "/Users/michaellefrancois/www/****/app/Scopes/TeamScope.php", [Object(Illuminate\Database\Eloquent\Builder), Object(App\Models\Ticket)])
```

**Comment by mpociot** [comment]
In the project settings you can define a custom preload code. This code will be evaluated before Invoker queries your models, accesses mails etc. 
so in there you could login a known user and those scopes should work just fine then.

**Comment by lefrancois** [comment]
That's great, thanks for the info 👍🏼
