### ISSUE TITLE
Nova Handle Report Problem

### ISSUE THREAD

**Issue by rexliu0715** [beyondcode/invoker-community#174]
------
**OS**: darwin
**Invoker Version**: 2.4.0
**Laravel Version**: 8.19.0
**Local project**: unknown
**PHP Binary**: /usr/local/bin/php
**Route**: /home?project=local-sRKw5cHCr3L1jEpStwJiP8

**Error**:
```
PHP Fatal error:  Declaration of App\Exceptions\NovaHandler::report(Exception $exception) must be compatible with Laravel\Nova\Exceptions\NovaExceptionHandler::report(Throwable $e) in /home/erp/webapps/erp/app/Exceptions/NovaHandler.php on line 10
```

------
Symfony\Component\ErrorHandler\Error\FatalError
Declaration of App\Exceptions\NovaHandler::report(Exception $exception) must be compatible with Laravel\Nova\Exceptions\NovaExceptionHandler::report(Throwable $e)

------
use Exception;
use Laravel\Nova\Exceptions\NovaExceptionHandler;
class NovaHandler extends NovaExceptionHandler
{
    public function report(Exception $exception)
    {
        // Sentry - https://docs.sentry.io/platforms/php/laravel/#laravel-5x
        if (app()->bound('sentry') && $this->shouldReport($exception)) {
            app('sentry')->captureException($exception);
        }

**Comment by mpociot** [comment]
It seems like your NovaHandler `report` method is incorrect. As the error suggests, it needs to be compatible with the parent class that it extends from.
Just change `Exception` to `Throwable` in the method definition.

This is actually not an error within Invoker, but an error that Invoker detected within your application.
