### ISSUE TITLE
enlightn not working with SSH

### ISSUE THREAD

**Issue by genesiscz** [beyondcode/invoker-community#175]
------
**OS**: darwin
**Invoker Version**: 2.4.0
**Laravel Version**: 8.31.0
**Local project**: unknown (SSH)
**PHP Binary**: /usr/local/bin/php
**Route**: /enlightn?project=remote-bYyhQJERTpjNY8YneMvbF6

**Error**:
```
SyntaxError: Unexpected token E in JSON at position 4
```

**Comment by mpociot** [comment]
Yeah, this is an issue with Enlightn itself. I'll open-source the plugin so that this can hopefully be fixed by the Enlightn devs :)
