### ISSUE TITLE
Paddle payments

### ISSUE THREAD

**Issue by kiwina** [beyondcode/invoker-community#176]
Hi, not sure if its possible as i never used paddle but, when you try to pay by paypal the only option is with a credit card and cannot use account funds to make a payment, witch is super annoying. Love to try Invoker but i'm not willing to put the charge on the CC.
Edit:
i did buy other products and there was the paypal account payment option.

**Comment by mpociot** [comment]
Hi!

this could be because of the way Paypal handles subscriptions, but I'm not sure about that.
We offer a refund if you're not happy without asking any questions though :D

But since all of the payment is handled by Paddle, I can't really change anything about this.
