### ISSUE TITLE
Unable to open local project 

### ISSUE THREAD

**Issue by albertorsesc** [beyondcode/invoker-community#177]
------
**OS**: Ubuntu 20.04 linux
**Invoker Version**: 2.4.0
**Laravel Version**: ^7.4|^8.0
**Local project**: true
**PHP Binary**: /usr/local/bin/php
**Route**: /home

**Error**:
```
Error: spawn /usr/local/bin/php ENOENT
```

**Description**: By opening a local laravel project it throws an error.

![image](https://user-images.githubusercontent.com/22654040/113653885-83083980-964b-11eb-8648-4304b4b026c4.png)

**Comment by mpociot** [comment]
You have to specify your local PHP binary in the Invoker settings. The error tells you that you don't have PHP installed in /usr/local/bin
