### ISSUE TITLE
I am getting the following error while registering a new license 

### ISSUE THREAD

**Issue by deepak-pradhan** [beyondcode/invoker-community#178]
------
**OS**: win32
**Invoker Version**: 2.4.0
**Laravel Version**: unknown
**Local project**: true
**PHP Binary**: /usr/local/bin/php
**Route**: /home

**Error**:
```
Error: spawn /usr/local/bin/php ENOENT
```

**Comment by mpociot** [comment]
Please make sure to select the correct local PHP binary in the Invoker settings. The error is caused, because Invoker tries to load PHP from a location where it doesn't exist.
