### ISSUE TITLE
remote db ORM refused

### ISSUE THREAD

**Issue by aemaddin** [beyondcode/invoker-community#179]
This error appears when I tried to use another db connection
for example : I have 2 mysql databases in different servers
first one is default database connection inside the application server
and other one is on asciisd server with another config/database connection

hint: this working good with me on ssh connection, so there is no issues on my config
------
**OS**: darwin
**Invoker Version**: 2.4.0
**Laravel Version**: 8.36.2
**Local project**: no - ssh project
**PHP Binary**: /usr/local/bin/php
**Route**: /project/index?class=App%5CModels%5CMt5GroupSymbol&time=1618256421921&project=1256934

**Error**:
```
Doctrine\DBAL\Driver\PDO\Exception 

  SQLSTATE[HY000] [1045] Access denied for user 'asciisd'@'localhost' (using password: YES)

  at reports.caveo.com.kw/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDO/Exception.php:18
     14▕ final class Exception extends PDOException
     15▕ {
     16▕     public static function new(\PDOException $exception): self
     17▕     {
  ➜  18▕         return new self($exception);
     19▕     }
     20▕ }
     21▕

      [2m+11 vendor frames [22m
  12  phar:///tmp/invoker.phar/src/Factories/AttributeCollection.php:25
      Illuminate\Database\Connection::getDoctrineSchemaManager()

  13  phar:///tmp/invoker.phar/src/Factories/AttributeCollection.php:15
      _HumbugBoxb27e6153cb07\Invoker\Factories\AttributeCollection::getColumns()
```

**Comment by mpociot** [comment]
How do you switch the configuration/connection?

**Comment by mechelon** [comment]
I will close this issue due to inactivity.

If this issue still exists, feel free to reopen and, if applicable, provide more details.
