### ISSUE TITLE
Invalid foreach in index.php

### ISSUE THREAD

**Issue by jeffgreco13** [beyondcode/invoker-community#180]
------
**OS**: darwin
**Invoker Version**: 2.4.0
**Laravel Version**: 8.34.0
**Local project**: true
**PHP Binary**: /usr/local/bin/php
**Route**: /enlightn?project=local-wY2kkYXgPETUHgAKhvQBQQ

**Error**:
```
In index.php line 22:
                                           
  Invalid argument supplied for foreach()  
                                           

enlightn <path>
```

**Comment by mpociot** [comment]
Yeah, this is an issue with Enlightn itself. I'll open-source the plugin so that this can hopefully be fixed by the Enlightn devs :)
