### ISSUE TITLE
[Bug] route:list - columns field type error

### ISSUE THREAD

**Issue by geekish** [beyondcode/invoker-community#181]
<img width="408" alt="Screen Shot 2021-04-16 at 12 22 06 PM" src="https://user-images.githubusercontent.com/684339/115061127-615e4c00-9eae-11eb-90ab-7a4ae132df72.png">

Based on the help text, I would expect this to work as it does in CLI. I've tried spaces after commas, and just a single column. Here's the error modal:

<img width="565" alt="Screen Shot 2021-04-16 at 12 23 57 PM" src="https://user-images.githubusercontent.com/684339/115061310-a5515100-9eae-11eb-95e4-0512caf00d81.png">

**Comment by mpociot** [comment]
Thanks for reporting this! This will be fixed in the next release
