### ISSUE TITLE
Clear ssh key for specific connection

### ISSUE THREAD

**Issue by orediggerco** [beyondcode/invoker-community#182]
I have a default ssh key set which I use for my physical hosts/vms, but I have some apps hosted in platforms that do not use keys (Cloud Foundry), so I need to be able to clear the default key for specific connections and only use username/password. Is there a way to do that? I haven't found an existing issue here, in the docs, or a way to do so n Invoker.

I'm using the Mac version 2.4.0, on MacOS 10.15.7 (19H15).

**Comment by mpociot** [comment]
Thanks for reporting this. The next version will allow you to customize the authentication method:

![image](https://user-images.githubusercontent.com/804684/116364870-f2b1b480-a804-11eb-990f-c06c5a94bd41.png)
