### ISSUE TITLE
Can't scroll past x amount of models in the model browser

### ISSUE THREAD

**Issue by paperscissors** [beyondcode/invoker-community#186]
------
**OS**: darwin
**Invoker Version**: 2.4.0
**Laravel Version**: 7.30.4
**Local project**: unknown
**PHP Binary**: /usr/local/bin/php
**Route**: /project/index?class=App%5CEntities%5CUser&time=1619460234712&project=remote-ndSumDKQGnHzs5fiMmTgkz

**Error**:
The model browser stops letting you scroll the models list after 28 models. Seems like there's some finite boundary set there. This is somewhat of an edge case, so thought y'all should know.

**Comment by mpociot** [comment]
Could you provide a screenshot? What is your pagination setting? I'm unable to reproduce this error.
