### ISSUE TITLE
Call to undefined method Illuminate\Container\Container::version() while trying to connect via SSH

### ISSUE THREAD

**Issue by genesiscz** [beyondcode/invoker-community#189]
Trying to connect to the project via  SSH  
------
**OS**: win32
**Invoker Version**: 2.4.0
**Laravel Version**: 8.40
**PHP Binary**: /usr/local/bin/php
**Route**: /home?project=remote-fqCrPBPMpcmksRtvXzugFK

**Error**:
```
PHP Fatal error:  Uncaught Error: Call to undefined method Illuminate\Container\Container::version() in phar:///tmp/invoker.phar/vendor/illuminate/support/helpers.php:265
Stack trace:
#0 /data/speeder.phpcode.eu/bootstrap/app.php(17): env()
#1 phar:///tmp/invoker.phar/invoker.php(8): require_once('...')
#2 /tmp/invoker.phar(12): require('...')
#3 {main}
  thrown in phar:///tmp/invoker.phar/vendor/illuminate/support/helpers.php on line 265
```

**Comment by genesiscz** [comment]
Related:
https://github.com/beyondcode/invoker-community/issues/48

calling app()->version() in my remote app worked.

**Comment by mpociot** [comment]
It looks like you've also modified your `data/speeder.phpcode.eu/bootstrap/app.php(17)` file.

There usually is no env method call in this place.
If possible, try to avoid an `env` call there, possibly by accessing the `$_ENV` global variable instead.

**Comment by genesiscz** [comment]
@mpociot could you edit your comment to delete the domain name? I don't think it hurts a lot but still, you know :-)

That helped, thanks!
