### ISSUE TITLE
Bug: Unable to run a command with a $this->choice

### ISSUE THREAD

**Issue by Arnd-Jan** [beyondcode/invoker-community#193]
Invoker won't let me choose an option of a choice in a Laravel command. 

            
------
**OS**: darwin
**Invoker Version**: 2.4.0
**Laravel Version**: 8.36.2
**Local project**: true
**PHP Binary**: /usr/local/bin/php
**Route**: /plugins?project=local-q3MeTdRYcWieF5wQbdsqyU

**Error**:
```
Aborted.
```

**Comment by mechelon** [comment]
Related to #62
