### ISSUE TITLE
can't open local project on windows

### ISSUE THREAD

**Issue by rockyru** [beyondcode/invoker-community#194]
------
**OS**: win32
**Invoker Version**: 2.4.0
**Laravel Version**: unknown
**Local project**: true
**PHP Binary**: /usr/local/bin/php
**Route**: /home?project=local-rEsFHdGa6PiANqRYAEs9u4

**Error**:
```
Error: spawn /usr/local/bin/php ENOENT
```

**Comment by sschlein** [comment]
Please select your correct PHP version in the settings. This error only happens if a wrong PHP binary was detected.

**Comment by rockyru** [comment]
Hi @sschlein , yep rookie mistake. My bad. Thank you!
