### ISSUE TITLE
Feature: Run Envoy commands

### ISSUE THREAD

**Issue by lefrancois** [beyondcode/invoker-community#195]
Hi there,

how about a section for running Envoy commands, similar to the artisan console commands?

Best,
Michael

**Comment by mpociot** [comment]
We don't have any plans to add first party support for this, but it sounds like a great idea for an Invoker plugin 🙂

**Comment by lefrancois** [comment]
Thanks for the hint 😉 Will try to do that, or in other words:

It's Friiiiidaaaaay,
will code that Saturday, Sunday
WORK!

Have a nice weekend!
