### ISSUE TITLE
Calling to static relation function when opening panel

### ISSUE THREAD

**Issue by jonkootje** [beyondcode/invoker-community#197]
When I try to open the panel for this belongsToMany relation in invoker, I see it is trying to call App\Models\Room::buildings(). This would mean this function has to be static which it shouldn't be. After I close this error message the relation also shows and works fine.             
------
**OS**: win32
**Invoker Version**: 2.4.0
**Laravel Version**: 8.40.0
**Local project**: true
**PHP Binary**: C:\laragon\bin\php\php-7.4.14-Win32-vc15-x64\php.exe
**Route**: /project/show?id=1&class=App%5CModels%5CUser&project=local-3HhTnEPWTpiaPqQSeE7Wwc

**Error**:
```
BadMethodCallException 

  Call to undefined method App\Models\Room::buildings()

  at C:\laragon\www\voortman-api\vendor\laravel\framework\src\Illuminate\Support\Traits\ForwardsCalls.php:50
     46▕      * @throws \BadMethodCallException
     47▕      */
     48▕     protected static function throwBadMethodCallException($method)
     49▕     {
  ➜  50▕         throw new BadMethodCallException(sprintf(
     51▕             'Call to undefined method %s::%s()', static::class, $method
     52▕         ));
     53▕     }
     54▕ }

  • Bad Method Call: Did you mean App\Models\Room::building() ? 

  1   C:\laragon\www\voortman-api\vendor\laravel\framework\src\Illuminate\Support\Traits\ForwardsCalls.php:36
      Illuminate\Database\Eloquent\Model::throwBadMethodCallException("buildings")

  2   C:\laragon\www\voortman-api\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php:1890
      Illuminate\Database\Eloquent\Model::forwardCallTo(Object(Illuminate\Database\Eloquent\Builder), "buildings", [])
```

**Comment by mpociot** [comment]
Are you calling this somewhere in your model? Is this a scope?
I don't know your model, so I can't really track the error down. Invoker must somehow try to call this method.

**Comment by mechelon** [comment]
I will close this issue due to inactivity.

If this issue still exists, feel free to reopen and, if applicable, provide more details.
