### ISSUE TITLE
BUG: Invoker Test Toolkit doesn't detect any tests.

### ISSUE THREAD

**Issue by sbrow** [beyondcode/invoker-community#198]
Tried with local folders and remote, no tests ever show up.

`phpunit.xml` file exists in the project directory (as generated by `laravel new`) and tests run fine from the command line.

**Comment by mpociot** [comment]
Could you please open up an issue in the plugin repository?
Thank you!

https://github.com/beyondcode/invoker-test-toolkit/issues
