### ISSUE TITLE
All unsignedTinyInteger columns displayed as booleans

### ISSUE THREAD

**Issue by bakerkretzmar** [beyondcode/invoker-community#2]
Loving Invoker so far! 😍

I have some `unsignedTinyInteger` columns that are used for enums (via [`bensampo/laravel-enum`](https://github.com/BenSampo/laravel-enum)) with only a few different values, e.g. `0`, `1`, `2`, or `3` for a user's `role`. Invoker thinks these columns are booleans and displays all the `0` values (superadmins) as `false` and everything else as `true`.

I thought this might be because Laravel's `boolean` column type is actually just an `unsignedTinyInteger`, but it looks like they do create slightly different column definitions (in MySQL):

`boolean`:

<img width="1094" alt="Screen Shot 2020-10-19 at 11 57 11 AM" src="https://user-images.githubusercontent.com/18192441/96475698-53cb5080-1202-11eb-9973-a635f41c31c1.png">

`unsignedTinyInteger` (my 'enum'):

<img width="1099" alt="Screen Shot 2020-10-19 at 11 56 57 AM" src="https://user-images.githubusercontent.com/18192441/96475709-55951400-1202-11eb-889a-973fd0a123a0.png">

I assume Invoker is inferring which columns are booleans based on something like this, so maybe it's possible to differentiate between `unsignedTinyInteger` and `boolean`? Not sure if there's a graceful way around this, and not sure how common my use case is.

The enum thing specifically definitely feels like a cool plugin though... 👀

**Comment by mpociot** [comment]
Invoker internally makes use of doctrine/dbal to detect column types. 
Unfortunately, DBAL returns the type "Boolean" for any tinyint column. It is also not possible to retrieve the column length via DBAL, so I don't really have a way to determine if the column is a tinyint meant to represent a boolean value, or if it is a tinyint meant to be an integer.

But as Invoker allows you to access your data through your Laravel model, you can fix this by manually casting the attribute in your model to an integer. This way, Invoker will not check the DBAL type, but instead use your manual cast:

```php
    protected $casts = [
        'organizer_type' => 'int',
    ];
```

Even though this does not give you access to the available values.

**Comment by bakerkretzmar** [comment]
@mpociot interesting, thanks! I actually just realized I'm custom casting one of these enum columns to the enum class itself, and that one displays as the integer value in Invoker. When I get around to updating the others that should fix this. Still a cool plugin idea too 😄
