### ISSUE TITLE
Error: Not connected/Unable to exec

### ISSUE THREAD

**Issue by schmidfelix** [beyondcode/invoker-community#20]
**Debug information:**
------
**OS**: darwin
**Invoker Version**: 2.0.1
**PHP Binary**: /usr/local/bin/php
**Route**: /project/show?id=19&class=App%5CModels%5CMigration&project=remote-9E9sGwsAqBZxb6JrWfBwfS

**Error**:
```
Error: Unable to exec
```

**Problem:**
------
When trying to open a model detail with 3 active/shown relationship panels I get this error:
![CleanShot 2021-02-02 at 10 33 22](https://user-images.githubusercontent.com/22103266/106580343-1638cc00-6542-11eb-8e25-28c4577fb14b.png)

After that every action I try to perform (for example: Executing code via Tinkerwell plugin, showing a model index, etc.) fails and I get the following error:

![CleanShot 2021-02-02 at 10 35 39](https://user-images.githubusercontent.com/22103266/106580617-6748c000-6542-11eb-8d47-b2a1f7695200.png)

When trying to open a model detail with only 1 relationship everything works as expected.

**Comment by mpociot** [comment]
I suppose you are connected to a server via SSH?
Could you take a look at the dev tools (you can open them via the Developer main menu item) and tell me if there are any errors popping up?

**Comment by schmidfelix** [comment]
I just wanted to add to the description that I've connected via SSH 😅

![CleanShot 2021-02-02 at 10 43 16](https://user-images.githubusercontent.com/22103266/106581710-79772e00-6543-11eb-9d83-02283b95a68b.png)

**Comment by mpociot** [comment]
Do you have some information about the SSH server? Is it a remote server or is it something like Homestead/Vagrant?

My gut feeling is that there are too many SSH connections at the same time or something like that 🤔 
I'll try to reproduce this locally

**Comment by schmidfelix** [comment]
Ah yeah, sorry.

The server is a VPS from Hetzner managed trough Ploi (similar to Forge). That could be the problem.
If you need any more information or logs of the server please let me know.

**Comment by schmidfelix** [comment]
When trying that locally everything works fine. So it just happens on a SSH connection

**Comment by brysonreece** [comment]
I'm currently receiving the same error message and output in DevTools while being connected to a server over SSH. I have a standard Forge-created t3.large instance through AWS and am able to load up more SSH connections externally from Invoker without dropped connections, so I'm unsure if it has to do with the server reaching it's maximum SSH connections.

**Comment by ThomasLaigneau** [comment]
------
**OS**: darwin
**Invoker Version**: 2.0.1
**PHP Binary**: /usr/local/bin/php
**Route**: /project/index?class=App%5CScrapingDetailPrice&time=1612296550922&project=1237229

**Error**:
```
Error: Not connected
```
Hi, I have the same error with a custom VPS (using Forge).

**Comment by Demers94** [comment]
I'm having the same problem , connecting via SSH to a WSL2 project

It happens when I'm loading a model that has many panels/relationships. I'm getting both `Error: (SSH) Channel open failure: open failed` and `Error: Unable to exec` shortly after. It seems to crash the SSH connection because after both of those errors occur, I start getting the `Error: Not connected` message and I have to restart Invoker if I try to do anything else

Debug info : 

------
**OS**: win32
**Invoker Version**: 2.0.2
**Laravel Version**: 8.25.0
**Local project**: unknown
**PHP Binary**: C:\laragon\bin\php\php-7.4.14-Win32-vc15-x64\php.exe
**Route**: /project/show?id=1&class=App%5CUser&project=remote-fEsf3QsR7WEnPix4ebsgmQ
```

**Comment by mpociot** [comment]
FYI: I fixed this and will publish an update later today/tomorrow.

If you're into technical details: https://github.com/beyondcode/invoker-community/issues/75#issuecomment-773405032
