### ISSUE TITLE
[Feature] Sync connections with Tinkerwell

### ISSUE THREAD

**Issue by pxlrbt** [beyondcode/invoker-community#201]
It's annoying to set up all connections twice for Tinkerwell and Invoker. Would be great if both tools would work better together and get a shared connection manager.

**Comment by mechelon** [comment]
This is currently not on our short-term roadmap, so I will close this for now. We might come back to this later.

You can still sync your servers via Forge of course. :) This is possible in Tinkerwell and Invoker as well.

**Comment by pxlrbt** [comment]
> You can still sync your servers via Forge of course. :) This is possible in Tinkerwell and Invoker as well.

Yeah. But that requires Forge 😅
