### ISSUE TITLE
[Feature] Open in Tinkerwell

### ISSUE THREAD

**Issue by pxlrbt** [beyondcode/invoker-community#202]
This feature requires a shared [connection manager](https://github.com/beyondcode/invoker-community/issues/201).
As Invoker's Tinkerwell Plugin is only a lightweight version of Tinkerwell I often find myself copying stuff over to Tinkerwell. Would be great to have an option to directly open the same project in Tinkerwell from Invoker.

**Comment by mechelon** [comment]
This is currently not on our short-term roadmap, so I will close this for now. We might come back to this later.
