### ISSUE TITLE
No team... can't export data from table

### ISSUE THREAD

**Issue by Batsirai** [beyondcode/invoker-community#207]
------
**OS**: darwin
**Invoker Version**: 2.5.0
**Laravel Version**: 7.30.4
**Local project**: unknown
**PHP Binary**: /usr/local/bin/php
**Route**: /project/index?class=App%5CData%5CModels%5CUser&time=1622763679104&project=remote-6KdR2VFTtt5LjRjWUTPPdR

**Error**:
```
Illuminate\Auth\Access\AuthorizationException 

  No team found

  at beta.quickstaffpro.com/releases/20210603110610/app/Data/Models/User.php:269
    265|             }
    266| 
    267|             if (!$this->_currentTeam) {
    268|                 session()->flush();
  > 269|                 throw new AuthorizationException('No team found');
    270|             }
    271| 
    272|             session(['current_team_id' => $this->_currentTeam->id]);
    273|         }

  1   beta.quickstaffpro.com/releases/20210603110610/app/Data/Models/User.php:210
      App\Data\Models\User::currentTeam()

      [2m+5 vendor frames [22m
  7   beta.quickstaffpro.com/releases/20210603110610/app/Data/Models/User.php:151
      Illuminate\Database\Eloquent\Model::__get()
```

**Comment by sschlein** [comment]
It sounds like Invoker is not able to detect the team – it depends how you've build this in your application, maybe you can use the preload code function in the settings to boot the team connection.


![CleanShot 2021-06-10 at 10 14 21@2x](https://user-images.githubusercontent.com/2911113/121489747-ab5a3e80-c9d4-11eb-87ed-e54c03a415d2.png)
