### ISSUE TITLE
Exception when see user

### ISSUE THREAD

**Issue by binaryk** [beyondcode/invoker-community#21]
------
**OS**: darwin
**Invoker Version**: 2.0.1
**PHP Binary**: /usr/local/bin/php
**Route**: /project/show?id=1&class=App%5CModels%5CUser&project=local-7Hth9fNLmsreiP23r1HjLX

**Error**:
```
In ShowResourceAction.php line 72:
                                                  
  Call to a member function setAppends() on null
```

**Comment by mpociot** [comment]
Hey @binaryk ,

does your User model have a global scope? That might cause the issue 🤔

**Comment by mpociot** [comment]
Nevermind, it was because of global scopes. Fixed it and it'll be available in the next release. I'm going to go through the issues and we'll release a new version tomorrow.
