### ISSUE TITLE
Empty error message

### ISSUE THREAD

**Issue by tomaserlebach** [beyondcode/invoker-community#210]
I am recieving an empty error message and i dont know why. As far as i can tell my laravel site is working fine. Any idea how to debug this problem?            
------
**OS**: darwin
**Invoker Version**: 2.5.0
**Laravel Version**: 8.32.1
**Local project**: true
**PHP Binary**: /usr/local/bin/php
**Route**: /project/index?class=App%5CModels%5CSurvey&time=1623278687088&project=local-jdhNmbwpni2nuHygrBiBoJ

**Error**:
```

```

**Comment by sschlein** [comment]
When do you receive the message?

**Comment by tomaserlebach** [comment]
As soon as I am selecting any model.
I will try out, this evening, to remove all models from the folder and put them back one by one. Maybe i am missing something.
It's hard to debug when the application is running well and there is no error message.
Laravel logs are empty too.

**Comment by mpociot** [comment]
We just released Invoker 1.5.1 - could you see if this fixed the error for you?

**Comment by tomaserlebach** [comment]
@mpociot The update fixed it! Works like a charm now 👍 Thanks a lot!
