### ISSUE TITLE
Add option to use other security certificates

### ISSUE THREAD

**Issue by sbc640964** [beyondcode/invoker-community#219]
I work on an ISP that requires traffic with its certificate only, I would be happy if you could allow certificates to be installed within the software.
I currently cannot install add-ons, I have this error:
![image](https://user-images.githubusercontent.com/46646044/122678558-0ae3f580-d1f0-11eb-9a13-16aa982b1c16.png)

**Comment by sschlein** [comment]
Hey, unfortunately, that is such an edge case that we can't add that for you only.

If there is no way around it please send me an email to support@beyondco.de and I'll give you a refund.
