### ISSUE TITLE
Disable global scopes

### ISSUE THREAD

**Issue by binaryk** [beyondcode/invoker-community#22]
Would be very useful if we can disable model global scopes.

**Comment by mpociot** [comment]
Yeah good idea. In the meantime you can disable it using a custom eloquent query filter. 
![image](https://user-images.githubusercontent.com/804684/106585094-40d95380-6547-11eb-88de-01424c0120a9.jpeg)

**Comment by binaryk** [comment]
That works for now! Hope we will have a way to see global scopes more obvious and disable them using a check box for example. 

Thank you!
