### ISSUE TITLE
Plugin not detected from a homestead project

### ISSUE THREAD

**Issue by fabgrondin** [beyondcode/invoker-community#220]
Invoker version : 2.5.2.0
OS : Windows 10

My project is opened through a ssh connection to homestead.

I followed the documentation for creating a plugin.

After building the plugin, Invoker does not load a simple context menu plugin from the invoker/plugins subfolder.

I only have an error :
`renderer.js:1 Connection :: sftp :: error Error: No such file
    at SFTPStream._transform (C:\Users\fgrondin\AppData\Local\Programs\Invoker\resources\app.asar\node_modules\ssh2-streams\lib\sftp.js:412:27)
    at SFTPStream.Transform._read (_stream_transform.js:191:10)
    at SFTPStream._read (C:\Users\fgrondin\AppData\Local\Programs\Invoker\resources\app.asar\node_modules\ssh2-streams\lib\sftp.js:183:15)
    at SFTPStream.Transform._write (_stream_transform.js:179:12)
    at doWrite (_stream_writable.js:403:12)
    at writeOrBuffer (_stream_writable.js:387:5)
    at SFTPStream.Writable.write (_stream_writable.js:318:11)
    at Channel.ondata (_stream_readable.js:716:22)
    at Channel.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)`

**Comment by mechelon** [comment]
You try to develop your plugin via SSH, right? I'm afraid that's not possible.
Our is it the usage of the plugin that doesn't work for you?

**Comment by fabgrondin** [comment]
The problem is not only for developing the plugin. The dist is built in the right project sub-folder and is correctly loaded when I open at local but not via ssh. I want to be sure there will be no problem in production for opening the project with the plugins.

**Comment by fabgrondin** [comment]
I found that the error seems to be triggered by the method invoker.detectRemoteProjectPlugins()
![image](https://user-images.githubusercontent.com/28737994/124277832-c9cfd780-db45-11eb-9f43-263c4c064c53.png)

**Comment by mechelon** [comment]
I'm afraid I have to ask again: How did you install the plugin on the server? By uploading the Plugin ZIP-File while connected to the project via SSH or somewhat other?

**Comment by fabgrondin** [comment]
I created the plugin using the template in a sub-folder of my project  : invoker/plugins/applicationplugin
I did `npm install` and `npm run prod`
According to the documentation : "This will write the production bundle to the dist folder. Your plugin is now ready to be commited to version control, in case you want to distribute it along with your project."
When I open the project locally, the plugin is loaded but not via ssh

**Comment by mechelon** [comment]
Ah, I think that's the problem and I will note that we have to improve this part in the docs.
Try the following:
- Build your plugin as described [here](https://beyondco.de/docs/invoker/plugins#buildingdistributing-your-plugin)
- Connect to your project via SSH
- Click on the plugins icon in the bottom left corner
- Click the »Load From Disk« button on the top right and select the plugin ZIP you just created
- Restart Invoker and connect via SSH again

That should do it.

**Comment by fabgrondin** [comment]
Ok thanks, 
I thought the plugins were automatically loaded per project without the need to distribute a zip file.
I will work this way
