### ISSUE TITLE
Cannot run invoker against production or staging environments

### ISSUE THREAD

**Issue by snapey** [beyondcode/invoker-community#221]
This is reported on behalf of my client, whom has the licence and has raised support issue as "CV"  

When connecting via SSH, invoker shows the following error;

![Invoker](https://user-images.githubusercontent.com/328747/124314199-eed64180-db69-11eb-94b9-f8ab4810cc54.png)

And the developer tools show

![Invoker](https://user-images.githubusercontent.com/328747/124314273-06152f00-db6a-11eb-99e5-897be3dc1938.png)
;
We see the same issue on two separate environments, but runs ok locally.

Both servers are Ubuntu 20.04.2 LTS
The deployment uses git to clone the repository, but only at depth=1
The deployment creates a new, timestamped folder, clones the project, runs composer install, fixes permissions, and then creates a symlink from the deployment directory to the 'Live' folder. The Live folder is served by nginx.

The same error occurs if invoker is pointed to the real project folder, not the symbolic link.

There is nothing else special about the servers.

**Comment by mpociot** [comment]
Is there anything within your actual application code that could throw such an error?
I can't see where this is coming from within Invoker, as we don't do anything that throws this error.

Maybe there's something in a service provider that uses git commands or something similar?

**Comment by snapey** [comment]
No, there is nothing in the code that knows about git.

**Comment by mechelon** [comment]
Can you reproduce the error with a default Laravel application?

**Comment by snapey** [comment]
My client cancelled his licence and it has now expired.
