### ISSUE TITLE
Throws `missing "handle" method` on Event class when dispatch button is clicked

### ISSUE THREAD

**Issue by tgeorgel** [beyondcode/invoker-community#222]
Hi there :)

I just started using the app — mainly for the model interface — and i'm pretty happy for now !
I wanted to use the "Event" section, it seems like events are not dispatched as expected 😕

When i click the "dispatch" button, after selecting a user in this case, the app crash because the event doesn't have the "handle" method, but it's a method we expect to find on the listener.. I am doing something wrong ?

Thank you :)

------
**OS**: darwin
**Invoker Version**: 2.5.2
**Laravel Version**: 5.8.38
**Local project**: true
**PHP Binary**: /usr/local/bin/php
**Route**: /events/details?class=App%5CEvents%5CCoachUpdated&project=local-6reDGskwkQMuN6fRHUdYmE

**Error**:
```
ReflectionException  : Method App\Events\CoachUpdated::handle() does not exist

  at /Users/tgeorgel/Documents/Projets/Protrainers/api/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:142
    138|             $callback = explode('::', $callback);
    139|         }
    140| 
    141|         return is_array($callback)
  > 142|                         ? new ReflectionMethod($callback[0], $callback[1])
    143|                         : new ReflectionFunction($callback);
    144|     }
    145| 
    146|     /**

  Exception trace:

  1   ReflectionMethod::__construct(Object(App\Events\CoachUpdated), "handle")
      /Users/tgeorgel/Documents/Projets/Protrainers/api/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:142

  2   Illuminate\Container\BoundMethod::getCallReflector()
      /Users/tgeorgel/Documents/Projets/Protrainers/api/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:120

  Please use the argument -v to see more details.
```

**Comment by mpociot** [comment]
This will be fixed in the next version 👍
