### ISSUE TITLE
Timeout during db:seed

### ISSUE THREAD

**Issue by emildayan** [beyondcode/invoker-community#223]
------
**OS**: win32
**Invoker Version**: 2.5.2
**Laravel Version**: 8.49.1
**Local project**: true
**PHP Binary**: C:\laragon\bin\php\php-8.0.7-Win32-vs16-x64\php.exe
**Route**: /commands?project=local-uRFLdmzsqzr8JbLY4mhUcm

**Error**:
```
Symfony\Component\ErrorHandler\Error\FatalError 

  Maximum execution time of 5000 seconds exceeded

  at phar://C:/Users/*/AppData/Local/Programs/Invoker/resources/invoker.phar/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:53
     49▕     }
     50▕     public function execute($params = null)
     51▕     {
     52▕         try {
  ➜  53▕             return parent::execute($params);
     54▕         } catch (\PDOException $exception) {
     55▕             throw \Doctrine\DBAL\Driver\PDO\Exception::new($exception);
     56▕         }
     57▕     }


   Whoops\Exception\ErrorException 

  Maximum execution time of 5000 seconds exceeded

  at phar://C:/Users/*/AppData/Local/Programs/Invoker/resources/invoker.phar/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:53
     49▕     }
     50▕     public function execute($params = null)
     51▕     {
     52▕         try {
  ➜  53▕             return parent::execute($params);
     54▕         } catch (\PDOException $exception) {
     55▕             throw \Doctrine\DBAL\Driver\PDO\Exception::new($exception);
     56▕         }
     57▕     }

  1   C:\laragon\www\*\vendor\filp\whoops\src\Whoops\Run.php:486
      Whoops\Run::handleError("Maximum execution time of 5000 seconds exceeded", "phar://C:/Users/*/AppData/Local/Programs/Invoker/resources/invoker.phar/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php")

  2   [internal]:0
      Whoops\Run::handleShutdown()
```

**Comment by mechelon** [comment]
Can you elaborate more about your seeders? Do you know how long these run outside of Invoker, e.g. via a CLI?

**Comment by emildayan** [comment]
> Can you elaborate more about your seeders? Do you know how long these run outside of Invoker, e.g. via a CLI?

About 2 hours via CLI. I'm guessing there's a hard set of 5000 seconds timeout? Perhaps a way to override this?

**Comment by mechelon** [comment]
We don't have a timeout set in Invoker. The timeout error is happening inside Doctrine/PDO – this takes the maximum execution time from the parameter `max_execution_time` (set in the `php.ini` which is defined in the PHP binary you set in the Invoker settings).

On the other hand we recommend running long-term tasks via the CLI. So I will close this for now.
