### ISSUE TITLE
invoker setting php on mamp pro

### ISSUE THREAD

**Issue by iebay90** [beyondcode/invoker-community#226]
------
**OS**: darwin
**Invoker Version**: 2.6.0
**Laravel Version**: unknown
**Local project**: true
**PHP Binary**: /Applications/MAMP/bin/php/php7.4.12/bin/php
**Route**: /home

**Error**:
```

```

**Comment by mechelon** [comment]
Can you elaborate on this issue? Without any error message or description it's hard to fix.

**Comment by mechelon** [comment]
I will close this issue due to inactivity.

If this issue still exists, feel free to reopen and, if applicable, provide more details.
