### ISSUE TITLE
[BUG] Cannot create new plugin

### ISSUE THREAD

**Issue by gander** [beyondcode/invoker-community#228]
Operating System | Program
---|--- 
_Linux Mint 20.2 Cinnamon_ | `Invoker-2.6.0.AppImage`

```
Error occurred in handler for 'createNavigationPlugin': Error: EACCES: permission denied, mkdir '/www/m15.localhost/invoker/plugins/t1'
    at Object.mkdirSync (fs.js:925:3)
    at module.exports.makeDirSync (/tmp/.mount_InvokeuMWfKN/resources/app.asar/node_modules/fs-extra/lib/mkdirs/make-dir.js:101:15)
    at t.value (/tmp/.mount_InvokeuMWfKN/resources/app.asar/dist/electron/main.js:1:88412)
    at /tmp/.mount_InvokeuMWfKN/resources/app.asar/dist/electron/main.js:1:97285
    at electron/js2c/browser_init.js:189:579
    at Object.<anonymous> (electron/js2c/browser_init.js:157:9339)
    at Object.emit (events.js:315:20) {
  errno: -13,
  syscall: 'mkdir',
  code: 'EACCES',
  path: '/www/m15.localhost/invoker/plugins/t1'
}
```

Docker base image is: [gander/dev](https://hub.docker.com/repository/docker/gander/dev).
Solution used: [How to use Invoker with docker containers?](https://dev.to/insolita/how-to-use-invoker-with-docker-containers-59a3)

The user who is logged in is `dev` (_1000_). Most things work fine. When I log into the container via ssh, I can execute this command without errors. If it creates the directory itself, the error still occurs.

![plugins](https://user-images.githubusercontent.com/421597/127742040-6bbd518f-3dc3-4e91-812a-44daab06cf64.gif)

**Comment by gander** [comment]
Given my intuition, I created this directory (`/www/m15.localhost/invoker/plugins`) in my local environment, outside of the container. The process went on. Files have been created. The plug-in project was created on the local computer, but in the path specified for the remote connection.

Ladies and gentlemen, how can it be done so badly? And I am supposed to use such a tool in a production environment, when its creators make such errors? **Unacceptable.**

**Comment by mpociot** [comment]
Looks like you found a bug in the plugin creation process.
Currently, Invoker plugins can only be developed using local projects. I have modified the plugin creation process, so that you don't run into this error again.
