### ISSUE TITLE
Can't view headings of widgets

### ISSUE THREAD

**Issue by larskoole** [beyondcode/invoker-community#229]
I've created 2 widgets but can't see their headings. This is with the fixed .phar I got from issue #227 so I don't know if it's an issue in 2.6.0 or only in the .phar (if the styling is even in the .phar of course).

![image](https://user-images.githubusercontent.com/8629456/127786505-3fcb38af-791a-4a31-89b5-a5f34ed8c693.png)

Edit: It seems to only be the headings of the "Trend" widgets. "Value" widgets work fine

**Comment by larskoole** [comment]
Just found out I can resize these widgets. When you first make them they are too small which causes the headings to hide.

(couldn't see the little black markings on the bottom right of each widget because of the dark theme)

**Comment by mechelon** [comment]
Thank you for pointing this out. The initial rendering of the widgets is indeed too small for the header to show and will be fixed together with the resizable handles in the next release. :)
