### ISSUE TITLE
Error on creating pivot table entry. (But entry is created nonetheless.)

### ISSUE THREAD

**Issue by sjardim** [beyondcode/invoker-community#23]
Freshly installed Invoker on my MacBookPro M1 running Big Sur. Tried to manually create a pivot table called "Watchlist" entry and got the following error. For some reason the where clause is trying to select an ID of 0. Screenshots attached. 

### On Models/User.php
```php
public function watchlists()
    {
        return $this->belongsToMany(Entity::class, 'watchlists')->withTimestamps();
    }
```

### On Models/Entity.php
```php
public function watchlists()
    {
        return $this->belongsToMany(User::class, 'watchlists')->withTimestamps();
    }
```

![CleanShot 2021-02-02 at 10 03 16@2x](https://user-images.githubusercontent.com/125217/106584508-32d30500-653e-11eb-9821-83ad62572baf.png)
![CleanShot 2021-02-02 at 10 03 37@2x](https://user-images.githubusercontent.com/125217/106584521-35355f00-653e-11eb-8743-6ce4952c2ae9.png)
            
------
**OS**: darwin
**Invoker Version**: 2.0.1
**PHP Binary**: /usr/local/bin/php
**Route**: /project/index?class=App%5CModels%5CWatchlist&time=1612260179193&project=local-6mn7wGuMvZM3fuVnpSyYF2

**Error**:
```
Illuminate\Database\QueryException 

  SQLSTATE[42S22]: Column not found: 1054 Unknown column 'id' in 'where clause' (SQL: select * from `watchlists` where `id` = 0 limit 1)

  at /Users/sjardim/Projects/wissee-new-dashboard/vendor/laravel/framework/src/Illuminate/Database/Connection.php:678
    674▕         // If an exception occurs when attempting to run a query, we'll format the error
    675▕         // message to include the bindings with SQL, which will make this exception a
    676▕         // lot more helpful to the developer instead of just the database's errors.
    677▕         catch (Exception $e) {
  ➜ 678▕             throw new QueryException(
    679▕                 $query, $this->prepareBindings($bindings), $e
    680▕             );
    681▕         }
    682▕

  • A column was not found: You might have forgotten to run your migrations. You can run your migrations using `php artisan migrate`. 
    https://laravel.com/docs/master/migrations#running-migrations

      [2m+12 vendor frames [22m
  13  phar:/Applications/Invoker.app/Contents/Resources/invoker.phar/src/Actions/ShowResourceAction.php:36
      Illuminate\Database\Eloquent\Builder::first()

  14  phar:/Applications/Invoker.app/Contents/Resources/invoker.phar/src/Actions/ShowResourceAction.php:24
      _HumbugBox7091da86deae\Invoker\Actions\ShowResourceAction::getEntry()
```

**Comment by sjardim** [comment]
Just saw that when I try to select the new pivot table entry, I got almost the same error, no it can't select a "undefined" ID.

**Comment by mpociot** [comment]
Thanks for reporting this. I will look into it tomorrow as we won't find the time for this at launch day 🙂

**Comment by sjardim** [comment]
> Thanks for reporting this. I will look into it tomorrow as we won't find the time for this at launch day 🙂

No problem and thank you! I can imagine how crazy a launch day can be. :)
