### ISSUE TITLE
Error running Enlightn on remote project.

### ISSUE THREAD

**Issue by JamesWoodford** [beyondcode/invoker-community#230]
------
**OS**: linux
**Invoker Version**: 2.6.1
**Laravel Version**: 8.52.0
**Local project**: unknown
**PHP Binary**: /usr/bin/php
**Route**: /enlightn?project=remote-a3nGHeiw4WwiQt7rS7Xkr2

**Error**:

![Screenshot_2021-08-02_15-24-55](https://user-images.githubusercontent.com/32905350/127869589-38a4055f-a030-4672-8376-85ac927c4a13.png)

I get this error when running Enlightn on a remote site but it runs OK on the local version.

I have seen that someone else had this error but I get a different message in the Dev Tools.

(FYI there is no index.php in my project that has a foreach on line 22)

Thanks.

**Comment by mechelon** [comment]
This is related to https://github.com/beyondcode/invoker-community/issues/180, even if you have a different error message. We will work something out with the team of Enlightn to fix this.
