### ISSUE TITLE
[FEATURE REQUEST] Tinkerwell plugin remember last code

### ISSUE THREAD

**Issue by gander** [beyondcode/invoker-community#232]
### Tinkerwell plugin remember last code

Really, it could use a Tinkerwell plugin to remember the last code run in it. I still have to remember to copy the code I am using, otherwise no trace of it remains after a restart.

**Comment by mechelon** [comment]
The Tinkerwell Plugin is just a basic version of Tinkerwell built into Invoker. For enhanced features we recommend installing [Tinkerwell](https://tinkerwell.app) itself :)
