### ISSUE TITLE
Nullable boolean fields show NULL as false

### ISSUE THREAD

**Issue by larskoole** [beyondcode/invoker-community#239]
As the title states, instead of a nullable boolean field showing NULL values, it shows false.

![image](https://user-images.githubusercontent.com/8629456/130254923-86a7e3ae-bc3b-4674-8c66-43e442f6d0c6.png)
In this case "feedback" is NULL but shows as false.

**Comment by mechelon** [comment]
Thank you for pointing this out, it's indeed a bug. Will be fixed in the next release. :)
