### ISSUE TITLE
[Bug]: Release notes version mismatch

### ISSUE THREAD

**Issue by gander** [beyondcode/invoker-community#242]
### Operating system

Linux Mint 20.2 Cinnamon

### Laravel Version

N/A

### PHP Version

N/A

### Project Location

Somewhere else (please specify in the description!)

### Bug description

If it's an update to 2.8.0 then I'd like to see what's new for 2.8.0

### Steps to reproduce

I launched Invoker today and the update window popped up with this message:

![invoker older release note](https://user-images.githubusercontent.com/421597/131827415-89b55bbe-3b7d-443d-b58a-ef5d26817eaf.png)

This information is also missing at https://beyondco.de/docs/invoker/release-notes

**Comment by sschlein** [comment]
Fixed – these are 2.8 release notes with a wrong headline

**Comment by gander** [comment]
@sschlein When will be update on https://beyondco.de/docs/invoker/release-notes ?

**Comment by sschlein** [comment]
I don't know, likely after I don't need to answer support requests anymore :-)

**Comment by sschlein** [comment]
https://beyondco.de/docs/invoker/release-notes/2-8-0
