### ISSUE TITLE
[Feature Request]: Quick Search for models

### ISSUE THREAD

**Issue by binaryk** [beyondcode/invoker-community#245]
### Feature Description

![CleanShot 2021-09-14 at 11 31 47@2x](https://user-images.githubusercontent.com/6833714/133224102-612dc921-ef1f-4a22-b025-e7ae9a2a888a.png)

**Comment by sschlein** [comment]
Hey – you can use the global search (CMD/CTRL+P) for that :-)

<img width="1690" alt="cleanshot_2021-09-14_at_10 35 45_2x" src="https://user-images.githubusercontent.com/2911113/133225101-785fe483-98c5-4ce3-af62-b1625b926b8c.png">
