### ISSUE TITLE
[Feature Request]: add alias to project

### ISSUE THREAD

**Issue by kife-design** [beyondcode/invoker-community#249]
### Feature Description

When starting a new client project i automatically create a predefined folder structure that organizes my designs, code, documents, ... 

These folders also have a standardized name: "01 - design", "02 - documents", ... "05 - code".

The problem with this setup is that all projects have the same name and you can only distinguish them by the folder.

Being able to give an alias to your project solves this issue.

### Is this feature valuable for other users as well and why?

I think i'm not the only one with this kind of setup, so i think this wil definitely be useful for other people.

**Comment by mechelon** [comment]
You are actually the first one to ask for this feature. I will leave this issue open for some time to look if other users wish for that as well. 
Feel free to comment or +1 if you think that's useful, too!
