### ISSUE TITLE
[Bug]: Error saving model (Cannot read property 'model' of undefined)

### ISSUE THREAD

**Issue by thomasjohnkane** [beyondcode/invoker-community#250]
### Operating system

macOS Mojave 10.14.6

### Laravel Version

v8.67.0

### PHP Version

8.0.10

### Project Location

Local

### Bug description

`TypeError: Cannot read property 'model' of undefined`

This error is logged to the console when I open the "create" modal for a given Model. The Model has a `json` column. The create function works as expected for the basic `user` Model.

Clicking "save" on this Model has no effect. The modal stays open and no errors are displayed. The record is not saved. This error is shown in the console after clicking save.

`Uncaught (in promise) TypeError: Cannot read property 'errors' of undefined`

### Steps to reproduce

Open modal, try to save model. Model migration is here:

```
Schema::create('scans', function (Blueprint $table) {
        $table->id();
        $table->string('scan_name');
        $table->string('team_name');
        $table->unsignedInteger('team_id');
        $table->string('provider');
        $table->string('schedule')->default('daily');
        $table->json('additional_attributes')->nullable();
        $table->dateTime('paused_at')->nullable();
        $table->softDeletes();
        $table->timestamps();
});
```

### Relevant log output

```shell
TypeError: Cannot read property 'model' of undefined
    at a.<anonymous> (renderer.js:1)
    at a.e._render (vendors.js:6)
    at a.r (vendors.js:6)
    at Fi.get (vendors.js:6)
    at new Fi (vendors.js:6)
    at vendors.js:6
    at a.rt.$mount (vendors.js:6)
    at a.rt.$mount (vendors.js:6)
    at init (vendors.js:6)
    at s (vendors.js:6)

Uncaught (in promise) TypeError: Cannot read property 'errors' of undefined
    at renderer.js:1
```

**Comment by mechelon** [comment]
Does this error appear only in specific cases – e.g. if you null the field, enter invalid json or something – or always?
Do you have a validation for this model?
