### ISSUE TITLE
Error: spawn /usr/local/bin/php ENOENT

### ISSUE THREAD

**Issue by spooksie** [beyondcode/invoker-community#251]
Fresh installation on my new Mac. Ive not changed any settings or anything. 

------
**OS**: darwin
**Invoker Version**: 2.8.0
**Laravel Version**: unknown
**Local project**: true
**PHP Binary**: /usr/local/bin/php
**Route**: /home

**Error**:
```
Error: spawn /usr/local/bin/php ENOENT
```

**Comment by spooksie** [comment]
MacOs 12

I solved it, as I installed PHP with homebrew, which installs to a different location. 

❯ which php
/opt/homebrew/bin/php

I went to settings and changed the path. It works now.

**Comment by mechelon** [comment]
I was asking because Apple removed PHP with Monterey (as far as I know) completely from the system. Checking the path was my next idea.

Glad you figured it out! 🎉
