### ISSUE TITLE
[Bug]: Model based on a database view shows blank results

### ISSUE THREAD

**Issue by ryanmortier** [beyondcode/invoker-community#252]
### Operating system

Windows 10

### Laravel Version

v8.68.1

### PHP Version

7.4

### Project Location

Remote (Server)

### Bug description

When trying to look at a model that is modelled off a database view rather than a table, the rows are all blank.

![image](https://user-images.githubusercontent.com/2053960/140174691-83f1af05-208a-4897-8f6a-bb9152d71746.png)

**Comment by sschlein** [comment]
Hey, I'm closing this because we don't do official support for this. According to the Laravel docs, that is not standard behavior and even if it works, we can't do support on this for Invoker.
