### ISSUE TITLE
Invoker suddenly doesn't load project on ElementaryOS (based on Ubuntu, Linux)

### ISSUE THREAD

**Issue by Ripplz** [beyondcode/invoker-community#253]
------
**OS**: linux
**Invoker Version**: 2.8.0
**Laravel Version**: unknown
**Local project**: unknown
**PHP Binary**: /usr/local/bin/php
**Route**: /home

**Error**:
```
PHP Fatal error:  Uncaught PharException: internal corruption of phar "/tmp/ubuntu_invoker.phar" (truncated manifest header) in /tmp/ubuntu_invoker.phar:10
Stack trace:
#0 /tmp/ubuntu_invoker.phar(10): Phar::mapPhar('box-auto-genera...')
#1 {main}
  thrown in /tmp/ubuntu_invoker.phar on line 10
```

**Comment by mechelon** [comment]
Hey, the word "suddenly" in your description as well as the corrupted file error hints that something changed on your system, so I assume reinstalling Invoker will help. :)

**Comment by Ripplz** [comment]
> Hey, the word "suddenly" in your description as well as the corrupted file error hints that something changed on your system, so I assume reinstalling Invoker will help. :)

I did try re-installing, but that didn't work. And I really do not think it was something that changed on my system - a colleague has the exact same issue with Invoke 2.8.0 on his own system. Just yesterday I tried downloading an older version (2.7.0) of Invoker, and it works, so I'm using that version for now.

**Comment by Ripplz** [comment]
how can I reopen this issue?
