### ISSUE TITLE
Unable to load dynamic library 'blackfire.so' 

### ISSUE THREAD

**Issue by skinnyandbald** [beyondcode/invoker-community#256]
------
**OS**: darwin
**Invoker Version**: 2.8.0
**Laravel Version**: 8.40.0
**Local project**: unknown
**PHP Binary**: /usr/local/bin/php
**Route**: /home?project=1471289

**Error**:
```
PHP Warning:  PHP Startup: Unable to load dynamic library 'blackfire.so' (tried: /usr/lib/php/20190902/blackfire.so (/usr/lib/php/20190902/blackfire.so: cannot open shared object file: No such file or directory), /usr/lib/php/20190902/blackfire.so.so (/usr/lib/php/20190902/blackfire.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
```

**Comment by mechelon** [comment]
This seems to be a problem with your PHP installation, since the path in the error as well as Blackfire has nothing to do with Invoker. 🤔
