### ISSUE TITLE
Cannot see model.

### ISSUE THREAD

**Issue by binaryk** [beyondcode/invoker-community#26]
------
**OS**: darwin
**Invoker Version**: 2.0.1
**PHP Binary**: /usr/local/bin/php
**Route**: /project/index?class=App%5CModels%5CMedia&time=1612262994723&project=1104334

**Error**:
```
In RelatedModelItem.php line 43:
                                                                     
  Unable to resolve the related model for relation: temporaryUpload  
  Please add @relatedModel doc block.
```

**Comment by mpociot** [comment]
Invoker is unable to resolve the model that is associated with your "temporaryUpload" relation.
This is the case when you have a "dynamic" relationship.

You can add a docblock to your relation to tell Invoker which class is related:

```php
@relatedModel \App\YourModel
```
