### ISSUE TITLE
Invoker not working with sail

### ISSUE THREAD

**Issue by mathewparet** [beyondcode/invoker-community#275]
Looks like invoker doesn't like Laravel Sail projects. I have a reason why my local PHP installation is v7.

------
**OS**: darwin
**Invoker Version**: 2.8.0
**Laravel Version**: unknown
**Local project**: true
**PHP Binary**: /usr/local/bin/php
**Route**: /home?project=local-3eXL9hWLtyRfqizUBd6RH3

**Error**:
```
Fatal error: Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 8.0.2". You are running 7.3.27. in /Users/mathewparet/Projects/fifa/vendor/composer/platform_check.php on line 24
```

**Comment by mechelon** [comment]
Invoker 2.13.0 now supports Docker for projects and therefore Sail too.
