### ISSUE TITLE
PHP 8.1 not supported: ParseToAstFailure when going to Jobs

### ISSUE THREAD

**Issue by ziming** [beyondcode/invoker-community#276]
------
**OS**: darwin
**Invoker Version**: 2.8.0
**Laravel Version**: 8.83.4
**Local project**: unknown
**PHP Binary**: /usr/local/bin/php
**Route**: /events?project=remote-2Qqm6z6oLNWQT4JxvZ3dUh

**Error**:
```
In ParseToAstFailure.php line 22:
                                                                               
  AST failed to parse in located source (in /home/forge/censored-my-site-name/rel  
  eases/20220311140050/vendor/dyrynda/laravel-model-uuid/src/GeneratesUuid.php)                                                                           
                                                                               

In Lexer.php line 197:
                           
  Undefined array key 403
```

**Comment by ziming** [comment]
If it help, the last time it worked fine, I was on PHP 8.0. Now I'm on PHP 8.1

**Comment by ziming** [comment]
@mpociot 

So I went to look at https://github.com/nikic/PHP-Parser/commits/master/lib/PhpParser/Lexer.php

And looking at the git history. I saw that they have a commit that add supports for PHP 8.1 for Lexer.php

https://github.com/nikic/PHP-Parser/commits/master/lib/PhpParser/Lexer.php

Since Invoker is closed source. I would like to ask if you have updated nikic/PHP-Parser to the latest version.

**Comment by mpociot** [comment]
This will be fixed in the next version 👍

**Comment by ziming** [comment]
Awesome!
