### ISSUE TITLE
I loaded my laravel project and the error pop up

### ISSUE THREAD

**Issue by crisstelista** [beyondcode/invoker-community#277]
------
**OS**: win32
**Invoker Version**: 2.8.0
**Laravel Version**: unknown
**Local project**: true
**PHP Binary**: /usr/local/bin/php
**Route**: /home

**Error**:
```
Error: spawn /usr/local/bin/php ENOENT
```

**Comment by mechelon** [comment]
Please make sure that you select your correct PHP binary in the Invoker settings.
