### ISSUE TITLE
[Feature Request]: Autofocus on group name input when creating a group

### ISSUE THREAD

**Issue by markwalet** [beyondcode/invoker-community#281]
### Feature Description

Just a small one.

After clicking the `New Group` button, I have to click on the `Group name` input before I can start typing. This can be automated.

### Is this feature valuable for other users as well and why?

I think so. It's a small detail that improves the productivity. Especially when you are creating multiple groups in one go.

**Comment by mechelon** [comment]
Thank you! Integrated in 2.9.0 :)
