### ISSUE TITLE
Add support for Apple Silicon chips

### ISSUE THREAD

**Issue by alexmck** [beyondcode/invoker-community#284]
### Feature Description

Thank you for Invoker. It's a real time saver. I've just upgraded to an M1 Mac and Invoker appears to be the only app I use that has no support for Apple Silicon.

Is it possible to get an Apple Silicon build of Invoker?

**Comment by hcaz** [comment]
I can see a download for apple silicon in the download section - https://beyondco.de/licenses/invoker

**Comment by alexmck** [comment]
Thank you! That definitely wasn't there when I posted this feature request (unless I'm going crazy!)

❤️

**Comment by mechelon** [comment]
Nope, you're not going crazy @alexmck, we released that one yesterday 😅
