### ISSUE TITLE
dd() does not work, dump() does

### ISSUE THREAD

**Issue by twdnhfr** [beyondcode/invoker-community#287]
Hey,

currently I'm using Invoker but the same issue is happening with Tinkerwell itself. When I write and execute any Code via the Tinkewell Plugin or Tinkerwell itself the dd() function does not work. To be more precise, any code containing a dd() will not execute.

This will execute and print the texts:
```
dump("before");
dump("after");
```

Nothing is printed with this:
```
dump("before");
dd("test");
dump("after");
```

------
**OS**: darwin
**Invoker Version**: 2.9.0
**Laravel Version**: 8.83.9
**Local project**: true
**PHP Binary**: /opt/homebrew/bin/php (8.1.4)

------

![Bildschirmfoto 2022-04-21 um 14 48 51](https://user-images.githubusercontent.com/13796752/164461483-2e594238-6604-4d88-ab1c-301601d8e5bf.png)

![Bildschirmfoto 2022-04-21 um 14 48 40](https://user-images.githubusercontent.com/13796752/164461488-f834c331-5866-4648-8640-a2d28255d817.png)

**Comment by mpociot** [comment]
This is a limitation of the Tinkerwell plugin - you might want to check out Tinkerwell v3 (which also adds autocomplete) for this.
