### ISSUE TITLE
Call to undefined method __invoke() on event

### ISSUE THREAD

**Issue by joostvanhoof** [beyondcode/invoker-community#294]
**OS**: darwin
**Invoker Version**: 2.8.0
**Laravel Version**: 9.14.1
**Local project**: true
**PHP Binary**: /opt/homebrew/Cellar/php/8.0.9/bin/php

I'm getting the following error when trying to dispatch an event through the Invoker UI:

`Call to undefined method App\Events\User\UserOnboarded::__invoke()`

My event is defined as below, which is more or less the same as how it would be defined when generating an event with `php artisan make:event`: using this command will also not generate the `__invoke()` method.

```php
namespace App\Events\User;

use App\Models\User;
use Illuminate\Foundation\Events\Dispatchable;
use Illuminate\Queue\SerializesModels;

class UserOnboarded
{
    use Dispatchable, SerializesModels;

    public $user;

    public function __construct(User $user)
    {
        $this->user = $user;
    }
}
```

**Comment by mpociot** [comment]
This will be fixed in the next version of Invoker.

**Comment by RealMrHex** [comment]
Same here!

**Comment by laocoi** [comment]
Use ```event``` instead of ```dispatch```

```event(new \App\Events\User\UserOnboarded());```
