### ISSUE TITLE
Previewing emails not working: class "Swift_Mailer" not found

### ISSUE THREAD

**Issue by joostvanhoof** [beyondcode/invoker-community#295]
**OS**: darwin
**Invoker Version**: 2.8.0
**Laravel Version**: 9.14.1
**Local project**: true
**PHP Binary**: /opt/homebrew/Cellar/php/8.0.9/bin/php
**Route**: /mails/details?class=App%5CMail%5COnboarding%5CWelcomeEmail&project=local-vJVWDzTaRcTmNRcxH4mwYX

When trying to preview an email I get `Class "Swift_Mailer" not found`. I'm running a pretty vanilla Laravel 9 installation, the Invoker documentation doesn't state I need a specific package to support previewing emails. Am I missing something?

**Comment by mechelon** [comment]
That's because Laravel 9 uses Symfony Mail instead of SwiftMailer for Mailables. We added support for this in version 2.9.0.

**Comment by joostvanhoof** [comment]
Thanks @mechelon! I just notice that I'm still on 2.8.0. If I click on Invoker > Check for Updates... nothing happens. How can I check that my license key is still eligible for updates?

**Comment by mechelon** [comment]
You can check this in the Beyond Code dashboard - either by logging in with your license (https://beyondco.de/license-login) or user account (https://beyondco.de/login).
