### ISSUE TITLE
Error: spawn /usr/local/bin/php ENOENT

### ISSUE THREAD

**Issue by lukebouch** [beyondcode/invoker-community#296]
I just downloaded Invoker for the first time and I keep getting an error every time I try to open a project.

------
**OS**: darwin
**Invoker Version**: 2.9.0
**Laravel Version**: unknown
**Local project**: true
**PHP Binary**: /usr/local/bin/php
**Route**: /home

**Error**:
```
Error: spawn /usr/local/bin/php ENOENT
```

**Comment by sschlein** [comment]
That sounds like Invoker has detected the wrong (or no) PHP binary. Can you check your settings
![CleanShot 2022-06-17 at 14 45 32@2x](https://user-images.githubusercontent.com/2911113/174300915-001c50c5-8da3-428a-b19c-980d9987c7f3.png)
?

**Comment by lukebouch** [comment]
That was it! I just correct the path to my install of PHP through Homebrew. Thanks
