### ISSUE TITLE
I encountered an error

### ISSUE THREAD

**Issue by bayrameker** [beyondcode/invoker-community#298]
------
**OS**: win32
**Invoker Version**: 2.9.0
**Laravel Version**: unknown
**Local project**: true
**PHP Binary**: /usr/local/bin/php
**Route**: /home?project=local-sqwEJfdgVCbcsTfMKLEvb7

**Error**:
```
Error: spawn /usr/local/bin/php ENOENT
```

**Comment by mechelon** [comment]
Sounds like Invoker has detected the wrong (or no) PHP binary. Can you double-check the PHP path in your preferences?
<img width="551" alt="CleanShot 2022-07-18 at 18 47 57@2x" src="https://user-images.githubusercontent.com/26432041/179561969-47674da6-d325-42a5-bc82-04d7f1b195d4.png">
