### ISSUE TITLE
[Bug]:  Invoker @ $135 for life-time ?

### ISSUE THREAD

**Issue by anjanesh** [beyondcode/invoker-community#299]
### Operating system

macOS Mojave > FireFox 102

### Laravel Version

NA

### PHP Version

NA

### Project Location

NA

### Bug description

Your life-time license for Invoker says $249 but when I tried to checkout its says Rs 10,618 (INR) which is ~$135.
 
Is this a bug or Indian pricing edition ?

https://imgur.com/a/CQfaaVs

PS: $79 is showing as USD 93.22 (incl. 14.22 tax)

**Comment by sschlein** [comment]
If we see VPN purchases from non PPP countries, you are violating our terms and conditions and we'll block you for all purchases and usages of all our apps – so that's not a recommendation but a terms violation that gets you blocked.

**Comment by anjanesh** [comment]
Perhaps I was misleading.

I am not using a VPN - I am from India - I entered that for Steps to reproduce.

So the pricing is separate for India ?

**Comment by sschlein** [comment]
You are good but you recommending this to people from other countries is not cool. Yes, we offer purchasing power parity and sell at a different price to some countries where the median income is lower than in Europe/the US

**Comment by anjanesh** [comment]
Thanks for clarification - I can see how this looks at a different angle - I was not trying to _recommend_ this - if this pricing was a bug and I bought it without knowing, then later on I would have had to pay the remaining amount to register the software.

I bought Nova for $299 because its a one-time fee. I normally don't get into recurring subscriptions products except for web hosting and the like. Hence my interest in Invoker too.
