### ISSUE TITLE
 Type of Invoker\Factories\FilterItem::$ignoreMissing must be bool 

### ISSUE THREAD

**Issue by CraftLogan** [beyondcode/invoker-community#3]
Not sure what is happening but get this on every single model in the app I am currently working in.

<img width="559" alt="Screen Shot 2020-10-25 at 6 00 33 PM" src="https://user-images.githubusercontent.com/10950466/97120269-1f690000-16ec-11eb-8b81-06e03a258595.png">

**Comment by mpociot** [comment]
I just published RC-8, which should be available in a couple of minutes. The bug occurred, when your local project makes use of `spatie/data-transfer-object`.
If you use RC-7, you can just check for updates.

**Comment by CraftLogan** [comment]
That fixed it. Thanks
