### ISSUE TITLE
Local project with Vapor core installed produces errors when "scan vendor folder" app is selected

### ISSUE THREAD

**Issue by jkudish** [beyondcode/invoker-community#300]
Heya,

I have some Models in my vendor folder that I wanted to include in Invoker so I turned on the scan vendors setting but it seems to have some kind of interference with the Vapor Core/Octane handler. 

* My composer packages are up to date and I run php 8.1.
* As soon as I restore that setting to only scan "app", the project has no issues opening
* There are no errors loading my application in general

Let me know if you have a solution or if I can produce further information.

Cheers 🍻

------
**OS**: darwin
**Invoker Version**: 2.9.0
**Laravel Version**: 9.18.0
**Local project**: true
**PHP Binary**: /usr/local/bin/php
**Route**: /home

**Error**:
```
Symfony\Component\ErrorHandler\Error\FatalError 

  Trait "Laravel\Octane\MarshalsPsr7RequestsAndResponses" not found

  at /Users/jkudish/dev/valet/turquoisegoat/vendor/laravel/vapor-core/src/Runtime/Handlers/OctaneHandler.php:11
      7▕ use Laravel\Vapor\Runtime\LambdaResponse;
      8▕ use Laravel\Vapor\Runtime\Octane\Octane;
      9▕ use Laravel\Vapor\Runtime\Octane\OctaneRequestContextFactory;
     10▕ 
  ➜  11▕ class OctaneHandler implements LambdaEventHandler
     12▕ {
     13▕     use MarshalsPsr7RequestsAndResponses;
     14▕ 
     15▕     /**


   Whoops\Exception\ErrorException 

  Trait "Laravel\Octane\MarshalsPsr7RequestsAndResponses" not found

  at /Users/jkudish/dev/valet/turquoisegoat/vendor/laravel/vapor-core/src/Runtime/Handlers/OctaneHandler.php:11
      7▕ use Laravel\Vapor\Runtime\LambdaResponse;
      8▕ use Laravel\Vapor\Runtime\Octane\Octane;
      9▕ use Laravel\Vapor\Runtime\Octane\OctaneRequestContextFactory;
     10▕ 
  ➜  11▕ class OctaneHandler implements LambdaEventHandler
     12▕ {
     13▕     use MarshalsPsr7RequestsAndResponses;
     14▕ 
     15▕     /**

      [2m+1 vendor frames [22m
  2   [internal]:0
      Whoops\Run::handleShutdown()
```

**Comment by jkudish** [comment]
Seems like an issue you've encountered before #248

**Comment by jkudish** [comment]
Upon further investigation, this seems to happen because `vapor-core` includes some references to files found in `laravel/octane` which isn't installed in my project. Normally, this isn't an issue as the `vapor-core` package doesn't load the octane runtime unless explicitly set. However, as a result of Reflection, Invoker does try to find that namespace.

I don't know if Invoker has a blacklist of packages not to scan, but a possible solution would be ignore `vapor-core` when scanning the `vendor` folder. Rationale being that `vapor-core` doesn't (and is unlikely to ever) have any models in it.

**Comment by mpociot** [comment]
We added `vapor-core` to our internal ignore-list and will release this in an upcoming version.
