### ISSUE TITLE
Trying to access my local project (with runs without error in both docker and in a production environment)

### ISSUE THREAD

**Issue by rickghome** [beyondcode/invoker-community#301]
------
**OS**: darwin
**Invoker Version**: 2.9.0
**Laravel Version**: 9
**Local project**: true
**PHP Binary**: /usr/local/bin/php
**Route**: /home

**Error**:
```
Error: spawn /usr/local/bin/php ENOENT
```

**Comment by mechelon** [comment]
Sounds like Invoker has detected the wrong (or no) PHP binary. Can you double-check the PHP path in your preferences?

<img width="551" alt="CleanShot 2022-07-18 at 18 47 57@2x" src="https://user-images.githubusercontent.com/26432041/179561812-1a69db54-0116-4f4e-85a8-676ad89cce39.png">

**Comment by rickghome** [comment]
Yes — I mentioned in a prior post that I noticed your tool had picked up the wrong PHP binary. When I switch it manually, this problem goes away. My other issues however remain. 

I really liked the idea of your tool, and hope to try it again soon.

Best,
rickg
