### ISSUE TITLE
[Bug]: Fails on Forge if using Envoyer

### ISSUE THREAD

**Issue by keyur555** [beyondcode/invoker-community#304]
### Operating system

macOs BigSur

### Laravel Version

latest

### PHP Version

PHP v8.07

### Project Location

Remote (Server)

### Bug description

Invoker can not load a project that uses Forge with Envoyer.io. It shows the error: Unsupported Laravel version detected.

### Steps to reproduce

Setup Envoyer.io on a Forge server where there is a "current" folder in the site directory/symlink that contains the whole application

### Relevant log output

```shell
Unsupported Laravel version detected.
```

**Comment by sschlein** [comment]
Did you set your project path to `/home/forge/domain/current/` or just to `/home/forge/domain`?

Envoyer deployments needs the `/current` path to work.

Please reopen the issue it that's not the case. Thanks
