### ISSUE TITLE
Something went wrong

### ISSUE THREAD

**Issue by mocap-lt** [beyondcode/invoker-community#305]
I just was opening my Laravel 9 project... and Invoker sowed this error.            
I'm on Win 10 Pro 64
------
**OS**: win32
**Invoker Version**: 2.9.0
**Laravel Version**: unknown
**Local project**: true
**PHP Binary**: /usr/local/bin/php
**Route**: /home

**Error**:
```
Error: spawn /usr/local/bin/php ENOENT
```

**Comment by sschlein** [comment]
Please select your correct local PHP binary, this error means that there is no PHP at this path. This path looks like a Linux/Mac path but your PHP at Windows is likely at C:\php\php.exe or C:\xampp\...\php.exe etc.

Invoker needs local PHP and does not work with Docker or WSL based setups at the moment. We are working on an update but don't have an ETA for this yet.

If you use multiple paths, please make sure to use the correct binary for your project.

**Comment by mocap-lt** [comment]
Thank you. It works.
You can put that info right in the Invoke app error message, so there will
be less bug reports / help requests.

All the best,
Vadim
