### ISSUE TITLE
Error on Jobs & Events Page

### ISSUE THREAD

**Issue by ziming** [beyondcode/invoker-community#313]
No Jobs are shown too.
            
------
**OS**: darwin
**Invoker Version**: 2.9.0
**Laravel Version**: 9.32.0
**Local project**: unknown
**PHP Binary**: /usr/local/bin/php
**Route**: /events?project=remote-2Qqm6z6oLNWQT4JxvZ3dUh

**Error**:
```
In ReflectionSourceStubber.php line 345:
                                                                               
  _HumbugBoxf4b902e0e9ad\Roave\BetterReflection\SourceLocator\SourceStubber\R  
  eflectionSourceStubber::formatType(): Argument #1 ($type) must be of type R  
  eflectionNamedType, ReflectionUnionType given, called in phar:///tmp/forge_  
  invoker.phar/vendor/roave/better-reflection/src/SourceLocator/SourceStubber  
  /ReflectionSourceStubber.php on line 334
```

**Comment by mpociot** [comment]
This will be fixed in the upcoming version.

Could you share the code for one of the jobs that isn't showing up?
