### ISSUE TITLE
Getting this error with 2.10.0 on Linux on launch.

### ISSUE THREAD

**Issue by curtsheller** [beyondcode/invoker-community#319]
------
**OS**: linux
**Invoker Version**: 2.10.0
**Laravel Version**: unknown
**Local project**: true
**PHP Binary**: /usr/local/bin/php
**Route**: /home

**Error**:
```
Error: spawn /usr/local/bin/php ENOENT
```

**Comment by mechelon** [comment]
Sounds like Invoker has detected the wrong (or no) PHP binary. Can you double-check the PHP path in your preferences?

<img width="551" alt="CleanShot 2022-07-18 at 18 47 57@2x" src="https://user-images.githubusercontent.com/26432041/179561812-1a69db54-0116-4f4e-85a8-676ad89cce39.png">
