### ISSUE TITLE
Tinkerwell Plugin: Request to make panels resizable

### ISSUE THREAD

**Issue by deanlj** [beyondcode/invoker-community#32]
Would love to see resizeable panels in the tinkerwell plugin

**Comment by ndeblauw** [comment]
And while at it, maybe the possibility to enlarge/shrink the font size

**Comment by dhruva81** [comment]
Any dark mode :)

**Comment by mechelon** [comment]
This is currently not on our short-term roadmap, so I will close this for now. We might come back to this later.

**Comment by deanlj** [comment]
ok thanks

i'll stick with the tinkerwell app for now then, shame
