### ISSUE TITLE
Error with local project

### ISSUE THREAD

**Issue by NAIJULU** [beyondcode/invoker-community#322]
------
**OS**: darwin
**Invoker Version**: 2.10.0
**Laravel Version**: unknown
**Local project**: true
**PHP Binary**: /usr/local/bin/php
**Route**: /home

**Error**:
```
Error: spawn /usr/local/bin/php ENOENT
```

**Comment by mechelon** [comment]
Looks like Invoker has detected the wrong (or no) PHP binary. Can you double-check the PHP path in your preferences?

<img width="551" alt="CleanShot 2022-07-18 at 18 47 57@2x" src="https://user-images.githubusercontent.com/26432041/179561812-1a69db54-0116-4f4e-85a8-676ad89cce39.png">

**Comment by shinwarismail** [comment]
In my case using XAMPP is like this

`"php.validate.executablePath": "C:/xampp/php/php.exe"`

**Comment by mpociot** [comment]
Please make sure that you have configured your local PHP executable correctly.
