### ISSUE TITLE
Invoker 2.0.1 can't open project

### ISSUE THREAD

**Issue by mc0de** [beyondcode/invoker-community#33]
This happens to one particular project, other projects seems fine but I only tried it on few of them because I just subbed for Invoker.

I allready checked on `~/.config/Invoker/` for more logs or information but didn't find anything useful.

Debug info:
```
------
**OS**: linux
**Invoker Version**: 2.0.1
**PHP Binary**: /usr/bin/php
**Route**: /home

**Error**:
```

Another note: by default Invoker looks up for php in `/usr/local/bin/php` which is not the case for linux systems, it would be nice to have nice error message that php is not found, or just display a dialog on first run to enter this path. Also, it has `spawn` command as a dependency, which is also not the case that many systems will have it.

**Comment by mpociot** [comment]
Can you take a look at the dev tools console (you can open it through the "Developer" menu) and take a screenshot? I'm not sure how to reproduce this issue, so this might help :)

**Comment by oniice** [comment]
@mpociot - I did a bit more digging into my project which wasn't opening, and giving the same error (#50) 

Looks like my `VerificationController` had was referencing the `Illuminate\Foundation\Auth\VerifiesEmails` trait, which didn't exist for some reason. So something must have been happening in Invoker do do with that, and explains why I was also reference to a `/home` route, which I don't have. Once I reran composer update and the class was present, it opened without error.
So could be some sort of similar issue, with invalid import referencing?

Hope that extra bit of info can help :)

**Comment by mc0de** [comment]
@mpociot here you go, if this can help with something
![Console](https://user-images.githubusercontent.com/8727992/106744119-01ceff00-6628-11eb-974c-15fadb8d1e36.png)

Neither `composer update` helps, project is maintained daily but and i tried that anyway without luck.

Some idea would be throw parsing exception if Invoker doesn't like some references or broken paths (which im sure is not the case but you never know, might be worth trying). Similar to notifications in console we had on composer v1 when breaking PSR-4 standards.

Another idea would to add flag when launching Invboker to write more extensive debug log.

@oniice well, we don't use any of these `VerificationController` or `VerifiesEmails`

**Comment by mc0de** [comment]
@mpociot since i can't share codebase, im willing to participate in regards of this case, even on another channel after work.

**Comment by mpociot** [comment]
@mc0de Thank you. Does this error only occur with the "Scan vendor folder" option enabled?

**Comment by mc0de** [comment]
@mpociot this happens with either option

**Comment by mitchellmusarra** [comment]
I'm seeing near-identical behaviour to that described by @mc0de - I will have time later today to dig into it but for now I'll watch this issue.

This issue is only present with one of my projects (of 3), but right now I can't think of any distinguishing factors.

Are there any other debugging methods I could try? 

Awesome product by the way @mpociot !

> ------
**OS**: darwin
**Invoker Version**: 2.0.2
**Laravel Version**: 8.26.1
**Local project**: true
**PHP Binary**: /usr/local/bin/php
**Route**: /home?project=local-xeJXknLUnyGWkeoXQxarQz

**Error**:
```

```

<img width="1223" alt="Screen Shot 2021-02-04 at 7 28 20 am" src="https://user-images.githubusercontent.com/73764291/106805258-97b36a00-66ba-11eb-8afe-62e2403bf652.png">

**Comment by mitchellmusarra** [comment]
Just to provide an update - the cause of my specific issue was that my PHP memory limit was set too low. Changing memory to 1024mb resolved the issue. :)

**Comment by LTKort** [comment]
Same here, few projects work another few don't. 
<img width="836" alt="Screenshot 2021-02-05 at 12 03 36" src="https://user-images.githubusercontent.com/2412670/107025786-2eab1f80-67aa-11eb-8753-44a7080aa2eb.png">

**Comment by mc0de** [comment]
it looks like option to set memory limit explicitly for Invoker would be very useful, because now it limits Invoker's ability to work at all and I wouldn't like to mess with global memory limit because it is useful to have limits for projects beeing developed.

**Comment by mpociot** [comment]
I'll adjust the memory limit when calling PHP from within Invoker so you don't need to manually configure anything 👍

**Comment by mc0de** [comment]
@mpociot great
