### ISSUE TITLE
I'm not sure why I cant select any laravel project with invoker

### ISSUE THREAD

**Issue by StaffCollab** [beyondcode/invoker-community#337]
------
**OS**: win32
**Invoker Version**: 2.11.0
**Laravel Version**: unknown
**Local project**: true
**PHP Binary**: /usr/local/bin/php
**Route**: /home

**Error**:
```
Error: spawn /usr/local/bin/php ENOENT
```

**Comment by mechelon** [comment]
Sounds like Invoker has detected the wrong (or no) PHP binary. Can you double-check the PHP path in your preferences?
