### ISSUE TITLE
Not working when using SSH via Docker

### ISSUE THREAD

**Issue by madebycm** [beyondcode/invoker-community#338]
------
**OS**: darwin
**Invoker Version**: 2.12.1
**Laravel Version**: 10.7.1
**Local project**: unknown
**PHP Binary**: /opt/homebrew/Cellar/php/8.2.4/bin/php
**Route**: /project/index?class=App%5CModels%5CUser&time=1681406956537&project=remote-gViwwgy9uEnky8aeqLNRaP

**Error**:
```
Error 

  Call to undefined method Doctrine\DBAL\Connection::createSchemaManager()

  at /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php:1145
    1141▕     public function getDoctrineSchemaManager()
    1142▕     {
    1143▕         $connection = $this->getDoctrineConnection();
    1144▕ 
  ➜ 1145▕         return $connection->createSchemaManager();
    1146▕     }
    1147▕ 
    1148▕     /**
    1149▕      * Get the Doctrine DBAL database connection instance.

  1   phar:///tmp/root_10_invoker.phar/src/Factories/AttributeCollection.php:25
      Illuminate\Database\Connection::getDoctrineSchemaManager()

  2   phar:///tmp/root_10_invoker.phar/src/Factories/AttributeCollection.php:15
      _HumbugBox9e1567d4a95b\Invoker\Factories\AttributeCollection::getColumns("App\Models\User")
```

**Comment by mechelon** [comment]
Invoker does not support Docker. We are working on it, but don't have an ETA for this yet.

**Comment by philharmonie** [comment]
Bought it, now saw, that it is not working with docker. Useless, unfortunately, as Docker (sail) is the recommended dev setup for Laravel nowadays.

**Comment by mechelon** [comment]
@philharmonie Invoker 2.13.0 now supports Docker for projects, including Laravel Sail. :)
