### ISSUE TITLE
Please help

### ISSUE THREAD

**Issue by zeevx** [beyondcode/invoker-community#341]
------
**OS**: darwin
**Invoker Version**: 2.12.1
**Laravel Version**: 10.10.1
**Local project**: unknown
**PHP Binary**: /opt/homebrew/bin/php
**Route**: /project/index?class=App%5CModels%5CVisitor&time=1684236179815&project=remote-thnikmNbsMhAdMUJZfdqWj

**Error**:
```
In Connection.php line 1145:
                                                                            
  Call to undefined method Doctrine\DBAL\Connection::createSchemaManager()
```

**Comment by mpociot** [comment]
We just released version 2.13.0 
Could you please try this version?

**Comment by zeevx** [comment]
I updated it to Version 2.13.0 (2.13.0)
Same thing.

**Comment by zeevx** [comment]
I also notice that this error only occurs in my second project, the first one works fine.

**Comment by mpociot** [comment]
Could you share the composer.json file contents of this project?

**Comment by mechelon** [comment]
I will close this issue due to inactivity.

If this issue still exists, feel free to reopen and, if applicable, provide more details.
