### ISSUE TITLE
Error opening project on M2 Mac

### ISSUE THREAD

**Issue by pulley871** [beyondcode/invoker-community#345]
Using php via brew, have tried linking and unlinking the brew.
php commands run in the terminal.

Ran this on my intel mac two days ago with same setup and everything ran like it was supposed to.

 
------
**OS**: darwin
**Invoker Version**: 2.13.0
**Laravel Version**: unknown
**Local project**: true
**PHP Binary**: /usr/local/bin/php
**Route**: /home?project=local-tCueh4tGbMvP81fcXatfwv
<img width="1728" alt="Screenshot 2023-07-03 at 4 15 47 PM" src="https://github.com/beyondcode/invoker-community/assets/73911337/4c45f0b7-833a-41ae-a0ed-0177200ccc38">
**Error**:
```


Error: spawn /usr/local/bin/php ENOENT
```

**Comment by mechelon** [comment]
Sounds like Invoker has detected the wrong (or no) PHP binary. Can you double-check the PHP path in your preferences?

**Comment by adampatterson** [comment]
Thanks, The error message here to new users is very unclear.

Given how many are created and closed without response it would be nice to change the prompt to something more constructive. 

In my case an an M1 mac my PHP path was `/opt/homebrew/Cellar/php/8.2.8/bin/php`
