### ISSUE TITLE
Problem with using local projects after MacOS update to 13.4 (Apple Silicon)

### ISSUE THREAD

**Issue by spooksie** [beyondcode/invoker-community#348]
------
**OS**: darwin
**Invoker Version**: 2.13.0
**Laravel Version**: 10.1.5
**Local project**: true
**PHP Binary**: /opt/homebrew/Cellar/php@8.1/8.1.16/bin/php
**Route**: /home?project=remote-qxhjuZSCZcvkk7kZMB89UV

**Error**:
```

```

I updated my MacOS to Ventura 13.4 and I can't access any of my local projects with Invoker. It doesn't show an error message, it just says 'Ooops. It seems like something went wrong'

Any tips on how to get this working again?

**Comment by sschlein** [comment]
Do you have an Intel or Apple Silicon Mac? We seem to see issues on other tools with 13.4 on Apple Silicon but we haven't been able to pin them down on Intel yet. Our own Apple Silicon machines still run 13.3 but it looks like they need an update soon.

**Comment by spooksie** [comment]
Yup, I'm on Apple Silicon. Is there any fix?

**Comment by spooksie** [comment]
I managed to fix the problem. For some reason when you upgrade to 13.4 it changes the Php location.

Before: /opt/homebrew/Cellar/php@8.1/8.1.16/bin/php
After: /opt/homebrew/opt/php@8.1/bin/php
