### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by xpdeal** [beyondcode/invoker-community#349]
------
**OS**: linux
**Invoker Version**: 2.13.0
**Laravel Version**: unknown
**Local project**: true
**PHP Binary**: /usr/local/bin/php
**Route**: /home

Invoker-2.13.0.AppImage 
loading plugins :: /home/jordan/.config/Invoker/plugins
(node:144856) electron: The default of contextIsolation is deprecated and will be changing from false to true in a future release of Electron.  See https://github.com/electron/electron/issues/23506 for more information
Unable to install `vue-devtools`: 
 Error: Exited with code 9
    at ChildProcess.<anonymous> (/tmp/.mount_Invoke43k4tR/resources/app.asar/dist/electron/main.js:1:83858)

**Error**:
```
Error: spawn /usr/local/bin/php ENOENT
```

**Comment by mechelon** [comment]
Sounds like Invoker has detected the wrong (or no) PHP binary. Can you double-check the PHP path in your preferences?
