### ISSUE TITLE
one more time

### ISSUE THREAD

**Issue by xpdeal** [beyondcode/invoker-community#357]
------
**OS**: linux
**Invoker Version**: 2.13.2
**Laravel Version**: unknown
**Local project**: true
**PHP Binary**: /usr/local/bin/php
**Route**: /home

**Error**:
```
Error: spawn /usr/local/bin/php ENOENT
```

**Comment by sschlein** [comment]
Based on your other tickets, your php binary is at `/usr/bin/php` 😉
