### ISSUE TITLE
Call to undefined method Doctrine\DBAL\Connection::createSchemaManager()

### ISSUE THREAD

**Issue by kwilliams-rds** [beyondcode/invoker-community#362]
------
**OS**: darwin
**Invoker Version**: 2.9.0
**Laravel Version**: 10.24.0
**Local project**: true
**PHP Binary**: /opt/homebrew/bin/php
**Route**: /project/index?class=App%5CModels%5CUser&time=1695370273058&project=local-xj19gqM7hjxTWd5fdzQ3TU

**Error**:
```
Error 

  Call to undefined method Doctrine\DBAL\Connection::createSchemaManager()

  at /Users/williamsk/Code/willk/vendor/laravel/framework/src/Illuminate/Database/Connection.php:1227
    1223▕     public function getDoctrineSchemaManager()
    1224▕     {
    1225▕         $connection = $this->getDoctrineConnection();
    1226▕ 
  ➜ 1227▕         return $connection->createSchemaManager();
    1228▕     }
    1229▕ 
    1230▕     /**
    1231▕      * Get the Doctrine DBAL database connection instance.

  1   phar:/Applications/Invoker.app/Contents/Resources/invoker.phar/src/Factories/AttributeCollection.php:25
      Illuminate\Database\Connection::getDoctrineSchemaManager()

  2   phar:/Applications/Invoker.app/Contents/Resources/invoker.phar/src/Factories/AttributeCollection.php:15
      _HumbugBoxf4b902e0e9ad\Invoker\Factories\AttributeCollection::getColumns("App\Models\User")
```
<img width="960" alt="Screenshot 2023-09-22 at 4 11 58 AM" src="https://github.com/beyondcode/invoker-community/assets/60831974/d647f9dd-350b-46d5-9a77-8a7644197787">

I have not been able to get this program running consistently. This issue has been going on for a while. I even followed the previous steps via a thread in March this year around the same issue (Marked closed/resolved).  Marcel had mentioned closing Invoker 
and deleting the [render.log](https://github.com/beyondcode/invoker-community/issues/332) as well as checking to Laravel version

My **render.log** file shows the following: 

<img width="780" alt="Screenshot 2023-09-22 at 4 25 03 AM" src="https://github.com/beyondcode/invoker-community/assets/60831974/2bc8e20c-409d-4730-b995-e1f77ef4cd79">

I have tried a range of doctrine/dbal versions with no success.  I thought there may be an issue with doctrine so in my compser.json file I tried a "doctrine/dbal": "~3.5 || ~3.6.2" and then the most current stable version.

<img width="653" alt="Screenshot 2023-09-22 at 4 28 27 AM" src="https://github.com/beyondcode/invoker-community/assets/60831974/a34acd8a-8adb-43c4-836c-75150dde1655">

Perhaps some steps to try and reproduce:

- PHP ^8.1  (opt/homebrew/bin/php)
-  Composer version 2.5.8 (.composer/vendor/bin/laravel)
-  Laravel Installer 5.1.1
- using Laravel Valet (.composer/vendor/bin/valet) TLD .code
- Laravel Valet 4.3.0 (currently on latest )

Any help would be appreciated. Thank you.

**Comment by mechelon** [comment]
Can you please update Invoker to 2.13.1? This version fixed the problem.

**Comment by kwilliams-rds** [comment]
Thank you.
