### ISSUE TITLE
Deprecated ini_set when selecting a project

### ISSUE THREAD

**Issue by Aktarus006** [beyondcode/invoker-community#364]
------
**OS**: darwin
**Invoker Version**: 2.13.2
**Laravel Version**:  10
**Local project**: true
**PHP Binary**: /opt/homebrew/bin/php
**Route**: /home?project=local-6K76m84H48Uj8Wq7gVJXmY

**Error**:
```
Deprecated: ini_set(): assert.exception INI setting is deprecated in phar:///Applications/Invoker.app/Contents/Resources/invoker_l10.phar/invoker.php on line 10
{"success":true,"data":{"name":"root","namespaces":[{"name":"App","namespaces":[{"name":"Models","namespaces":[],"models":[{"name":"User","title":"Users","class":"App\\Models\\User","namespace":"App\\Models","path":"\/Users\/aktarus\/Dev\/laravel_learn\/app\/Models\/User.php","primaryKey":"id"}],"opened":true}],"models":[],"opened":true}],"models":[],"opened":false}}
```

Hello always get this error when selecting a project in invoker. Even when it is a fresh install of Laravel.
Anyone got the same issue ? Any fix ?

Thanks for the help

**Comment by proclame** [comment]
Ran into the same issue when switching PHP versions to PHP8.3 (8.3.1).
When switching to PHP 8.2, everything works fine.

assert.exception ini setting is deprecated as of 8.3, and seems this is being called by invoker.

**Comment by getorent** [comment]
i have the same problem
