### ISSUE TITLE
SSH errors

### ISSUE THREAD

**Issue by zembrowski** [beyondcode/invoker-community#37]
------
**OS**: darwin
**Invoker Version**: 2.0.1
**PHP Binary**: /usr/local/bin/php
**Route**: /home

**Error**:
```
Error: (SSH) Channel open failure: open failed
```

Having some trouble connecting to a project via SSH. Getting the above error. Attached dev console screenshot.
![Bildschirmfoto 2021-02-02 um 13 45 27](https://user-images.githubusercontent.com/2451083/106605951-cc5fde00-6561-11eb-8484-b9d010dd9ede.png)

No problems whatsoever connecting via Terminal using this key.

Before getting there I had to convert my OpenSSH to PEM with `ssh-keygen -p -m PEM -f ~/.ssh/private_key`. Otherwise I could not save the project connection settings, getting the errors below:
![Bildschirmfoto 2021-02-02 um 11 53 52](https://user-images.githubusercontent.com/2451083/106606055-f1545100-6561-11eb-808d-c41c08f26470.png)
![Bildschirmfoto 2021-02-02 um 11 53 58](https://user-images.githubusercontent.com/2451083/106606065-f44f4180-6561-11eb-9430-8b05c8574cf6.png)

**Comment by zembrowski** [comment]
FYI: This still occurs in Invoker 2.0.2

(Tried out on macOS 11.2 and macOS 10.15.7 with the same error result)

Is there anything more I could provide to tackle this issue?

**Comment by mpociot** [comment]
Could you show me a full screenshot of the devtools?
This could be an issue with the amount of maximum Sessions configured on your remote server. 
Do you have root access to it, or is it a shared host?

**Comment by zembrowski** [comment]
You're right: the `MaxSessions` in `/etc/ssh/sshd_config` was set to a custom value `3`. Changing it to default, solved my connection issues.

Thanks for the tip!
