### ISSUE TITLE
Cant connect with server

### ISSUE THREAD

**Issue by getorent** [beyondcode/invoker-community#373]
------
**OS**: darwin
**Invoker Version**: 2.13.2
**Laravel Version**: unknown
**Local project**: unknown
**PHP Binary**: /opt/homebrew/etc/php/8.3/php.ini
**Route**: /home

**Error**:
```
PHP Deprecated:  ini_set(): assert.exception INI setting is deprecated in phar:///tmp/forge_10_invoker.phar/invoker.php on line 10
```

**Comment by proclame** [comment]
Likely PHP is set to 8.3.
Same as  #364
