### ISSUE TITLE
Error when connecting to a project on Forge

### ISSUE THREAD

**Issue by ysrdevs** [beyondcode/invoker-community#374]
------
**OS**: darwin
**Invoker Version**: 2.13.2
**Laravel Version**: unknown
**Local project**: unknown
**PHP Binary**: /Users/ysr/Library/Application Support/Herd/bin/php83
**Route**: /home?project=2166991

**Error**:
```
PHP Deprecated:  ini_set(): assert.exception INI setting is deprecated in phar:///tmp/forge_10_invoker.phar/invoker.php on line 10
```

**Comment by proclame** [comment]
Likely your PHP setting is 8.3 ?
Same as issue  #364
