### ISSUE TITLE
Error when opening project

### ISSUE THREAD

**Issue by rickmartensnl** [beyondcode/invoker-community#375]
------
**OS**: darwin
**Invoker Version**: 2.13.2
**Laravel Version**: unknown
**Local project**: true
**PHP Binary**: /opt/homebrew/Cellar/php/8.3.0/bin/php
**Route**: /home?project=local-iKvU9i5N4NnjNaAhXHocjv

**Error**:
```
Deprecated: ini_set(): assert.exception INI setting is deprecated in phar:///Applications/Invoker.app/Contents/Resources/invoker_l10.phar/invoker.php on line 10
{"success":true,"data":{"name":"root","namespaces":[{"name":"App","namespaces":[{"name":"Models","namespaces":[],"models":[{"name":"User","title":"Users","class":"App\\Models\\User","namespace":"App\\Models","path":"\/Users\/rickmartens\/PhpstormProjects\/project\/app\/Models\/User.php","primaryKey":"id"}],"opened":true}],"models":[],"opened":true}],"models":[],"opened":false}}
```

**Comment by rickmartensnl** [comment]
Changing the php version to 8.2, fixes the issue, however I would like to see this fixed that I can use the latest version of php.

**Comment by proclame** [comment]
Same as  issue  #364

**Comment by tfevens** [comment]
#383 & #384 are duplicates of this.  Would be great to see this fixed.
