### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by hristoaleksandrov** [beyondcode/invoker-community#377]
------
**OS**: darwin
**Invoker Version**: 2.13.2
**Laravel Version**: unknown
**Local project**: true
**PHP Binary**: /Users/hristoaleksandrov/Library/Application Support/Herd/bin//php
**Route**: /home?project=local-4TxraRbvToYZporrSAfzJP

**Error**:
```
Deprecated: ini_set(): assert.exception INI setting is deprecated in phar:///Applications/Invoker.app/Contents/Resources/invoker_l10.phar/invoker.php on line 10
{"success":true,"data":{"name":"root","namespaces":[],"events":[],"opened":false}}
```

**Comment by hristoaleksandrov** [comment]
Seems like the issue is with laravel 10.39.0 ? I'm not sure what else could be causing it.

**Comment by hristothebteam** [comment]
Nevermind, Invoker does not work with PHP 8.3, needs to be looked into.

**Comment by hristoaleksandrov** [comment]
Nevermind, Invoker does not work with PHP 8.3, needs to be looked into.
