### ISSUE TITLE
Multi-tenancy

### ISSUE THREAD

**Issue by ninthspace** [beyondcode/invoker-community#38]
I have a couple of projects that are multi-tenant (in various ways - single database, multi-database) and Invoker cannot open them. The error is usually of this form:

------
**OS**: linux
**Invoker Version**: 2.0.1
**PHP Binary**: /usr/bin/php
**Route**: /home?project=local-vWxqM9EryR6ejYzJJq7fod

**Error**:
```

```

Invoker cannot (obviously) deduce what a tenant is, or how a tenant is determined, so it would be good to be able to specify some custom code that allows the setting of a default tenant and/or change it.

**Comment by mpociot** [comment]
How did you implement multi-tenancy in your apps?

**Comment by ninthspace** [comment]
Problems fixed! The problem doesn't occur in cases when I actually switch to the correct version of PHP for the app before using Invoker - duh, and if I fix some PHP errors - double duh. #53 pointed me in the latter direction.

**Comment by ninthspace** [comment]
Sorry, now that I've got Invoker running with my apps, I'll actually report the issues when accessing models:

Using https://github.com/spatie/laravel-multitenancy in a multi-database setup, where the tenant and database connection is established from a subdomain on a request gives me these types of error:

```
Illuminate\Database\QueryException 

  SQLSTATE[3D000]: Invalid catalog name: 1046 No database selected (SQL: select * from `item_groups` where `item_groups`.`deleted_at` is null limit 1)
```

Custom-developed multi-tenant in a single database setup, where the tenant is determined by the logged in User:

```
ErrorException 

  Trying to get property 'id' of non-object

  at /home/chris/Work/git/adsoot/app/Domains/Tenants/TenantOwnedScope.php:27
     23▕      * @param  Model  $model
     24▕      */
     25▕     public function apply(Builder $builder, Model $model)
     26▕     {
  ➜  27▕         $builder->where('tenant_id', '=', Tenant::current()->id);
     28▕     }
     29▕ 
     30▕     public function extend(Builder $builder): void
     31▕     {

  1   /home/chris/Work/git/adsoot/app/Domains/Tenants/TenantOwnedScope.php:27
      Illuminate\Foundation\Bootstrap\HandleExceptions::handleError()

      [2m+7 vendor frames [22m
  9   phar:///tmp/.mount_InvokeB7Afu4/resources/invoker.phar/src/Actions/GetModelDefinitionAction.php:34
      Illuminate\Database\Eloquent\Model::__call()
```

I think what we need is somewhere to specify code to run as part of setup, e.g. to allow us to specify a tenant that's being used (or really allow us to run any code). Or could this be done per project as a plugin?

**Comment by mpociot** [comment]
I'll close this in favor of #68, as I think that's what I'm aiming for
