### ISSUE TITLE
Stopped Working After Laravel Forge Project and Server Upgraded to PHP 8.3

### ISSUE THREAD

**Issue by kornatzky** [beyondcode/invoker-community#381]
------
**OS**: darwin
**Invoker Version**: 2.13.2
**Laravel Version**: unknown
**Local project**: unknown
**PHP Binary**: /usr/local/bin/php
**Route**: /home

**Error**:
```
PHP Deprecated:  ini_set(): assert.exception INI setting is deprecated in phar:///tmp/forge_10_invoker.phar/invoker.php on line 10
```

**Comment by tfevens** [comment]
Same issue as #375.

Hopefully, someday it'll be fixed.
