### ISSUE TITLE
DataTransferObjectError

### ISSUE THREAD

**Issue by mikeybeck** [beyondcode/invoker-community#4]
Hi, I get the error below when loading my project.  

I believe this error first started occurring in version 1.3.  I was hoping it'd be fixed in v2 but it doesn't look like it yet..  This is RC8, by the way.

Please let me know if you require further info.

```
Invoker\Support\DataTransferObject\DataTransferObjectError 

  Invalid type: expected `Invoker\Factories\ModelItem::primaryKey` to be of type `string`, instead got value `array`, which is array.

  at phar:///tmp/.mount_InvokeWEBhzi/resources/invoker.phar/src/Support/DataTransferObject/DataTransferObjectError.php:38
    34|         }
    35| 
    36|         $expectedTypes = implode(', ', $expectedTypes);
    37| 
  > 38|         return new self("Invalid type: expected `{$class}::{$field}` to be of type `{$expectedTypes}`, instead got value `{$value}`, which is {$currentType}.");
    39|     }
    40| 
    41|     public static function uninitialized(string $class, string $field): DataTransferObjectError
    42|     {

  1   phar:///tmp/.mount_InvokeWEBhzi/resources/invoker.phar/src/Support/DataTransferObject/DataTransferObject.php:68
      Invoker\Support\DataTransferObject\DataTransferObjectError::invalidType("Invoker\Factories\ModelItem", "primaryKey", "string", "array")

  2   phar:///tmp/.mount_InvokeWEBhzi/resources/invoker.phar/src/Factories/ModelItem.php:40
      Invoker\Support\DataTransferObject\DataTransferObject::__construct([])
```

**Comment by mpociot** [comment]
Can you tell me about the primary key for this specific model?

**Comment by mikeybeck** [comment]
Wow, thanks for the fast response!  

That's the thing.. I don't know which model it's failing on.  Have tried working it out but there are a lot of models in this project, so it's a time consuming process.  
Any tips for narrowing it down?

**Comment by mpociot** [comment]
Ah okay. But there's no model where you know that the primary key attribute is an array? Maybe some custom composite key solution?

I'll try to push an update that improves the error message on Monday. This is actually not the latest release candidate anyway - so maybe RC9 fixes that already. Even though I doubt it as it seems like this is model related.

**Comment by mikeybeck** [comment]
Ah.. Yes, there are several models where the primary key is an array, and yes, it's a custom composite key solution, very similar to [this](https://stackoverflow.com/questions/36332005/laravel-model-with-two-primary-keys-update#37076437).

If getting this kind of thing to work is going to be an issue, might it be possible to get Invoker to exclude these models somehow?

**Comment by mpociot** [comment]
Hi @mikeybeck 
I hope you had a great Christmas holiday. I just fixed this issue locally - right now by ignoring models that have custom composite key solutions. Supporting these in Invoker would require quite a lot of work, I'll see how common this will become when we publicly release Invoker, then we can prioritize this.

I'll upload the RC10 in 2021 😱
