### ISSUE TITLE
Prefill email in mailable

### ISSUE THREAD

**Issue by nick-wilkins** [beyondcode/invoker-community#40]
When previewing a Mailable, you can merge in data as you see fit. Be good to recognise an 'email' field and offer dummy email address to use as merge. Optional obviuosly

**Comment by mpociot** [comment]
What exactly do you mean?
Does your mailable have an `email` constructor argument? Could you attach a screenshot?

**Comment by nick-wilkins** [comment]
Actually ignore me ... my mail template has a:
{{ $email }}
But of course, theres no concrete way to know that this is an email address, other than making some string assumptions.
