### ISSUE TITLE
PHP binary path for Windows WSL

### ISSUE THREAD

**Issue by FR6** [beyondcode/invoker-community#42]
Is there a way to set the PHP binary path to a binary inside WSL?
Since in my current local setup PHP is installed inside WSL (Windows Subsystem for Linux).

**Comment by Demers94** [comment]
I'm having the same issue

I tried changing the `PHP binary path` in the settings but it doesn't let me select the PHP binary in WSL2 (I get the error "the name of the file cannot be resolved by the system")

**Comment by FR6** [comment]
I just found out how to make it work: You need to connect remotely via SSH.

But to be able to connect to SSH you have to change the port on the WSL SSH server since Windows already have a SSH server and using the port 22.

**Comment by Demers94** [comment]
@FR6 Would you mind showing your connection settings and explaining how to change the default WSL SSH port?

**Comment by FR6** [comment]
Yes sure.

Here is what i did to change the SSH server port on WSL:

First i reinstalled the SSH server:

```
sudo apt-get remove openssh-server
sudo apt-get install openssh-server
```

Changed those configurations:

`nano /etc/ssh/sshd_config`

- Port 2222
- PubkeyAuthentication no
- PasswordAuthentication yes

Restarted the server:

`sudo service ssh --full-restart`

Tested in Windows PowerShell (strangely it wasn't working with other SSH client i tried):

`ssh username@hostname -p 2222`

Use the same `username ` and `hostname ` that you usually use to login from your terminal.

Hope it helps!

**Comment by Demers94** [comment]
It worked perfectly, thank you so much!

**Comment by mpociot** [comment]
I'll add this to the documentation. Thank you for posting this @FR6
