### ISSUE TITLE
Error: Cannot parse privateKey: Failed to generate information to decrypt key.

### ISSUE THREAD

**Issue by kylewindfall** [beyondcode/invoker-community#44]
When I add my Forge API key all of my projects pulled in as expected,  but when I try to connect to any of them I get the following error:

Error: Cannot parse privateKey: Failed to generate information to decrypt key.

**Comment by kylewindfall** [comment]
This actually was an issue with the MacOS update this morning.

**Comment by sschlein** [comment]
How did you solve it?

**Comment by Batsirai** [comment]
I have this issue... first time trying to connect via SSH

not sure what to do...

**Comment by craigh411** [comment]
I got this error because I forgot to enter the passphrase for my ssh key, so invoker wasn't able to decrypt the private key. If you set a passphrase when you generated your SSH key then you will need to add that to the invoker settings as well.
