### ISSUE TITLE
JSONB column support

### ISSUE THREAD

**Issue by snellingio** [beyondcode/invoker-community#47]
Probably deserves it's own issue.

Also reported by @vilhelmjosander here: https://github.com/beyondcode/invoker-community/issues/30#issuecomment-771665711

------
**OS**: darwin
**Invoker Version**: 2.0.1
**PHP Binary**: /usr/local/bin/php
**Route**: /project/index?class=App%5CModels%5CPost&time=1612279974763&project=local-cMHKWqTeboBJcCFGL8hABs

**Error**:
```
_HumbugBox7091da86deae\Doctrine\DBAL\Exception 

  Unknown database type jsonb requested, _HumbugBox7091da86deae\Doctrine\DBAL\Platforms\PostgreSqlPlatform may not support it.

  at phar:/Applications/Invoker.app/Contents/Resources/invoker.phar/vendor/doctrine/dbal/lib/Doctrine/DBAL/Platforms/AbstractPlatform.php:179
    175▕             $this->initializeAllDoctrineTypeMappings();
    176▕         }
    177▕         $dbType = \strtolower($dbType);
    178▕         if (!isset($this->doctrineTypeMapping[$dbType])) {
  ➜ 179▕             throw new \_HumbugBox7091da86deae\Doctrine\DBAL\Exception('Unknown database type ' . $dbType . ' requested, ' . static::class . ' may not support it.');
    180▕         }
    181▕         return $this->doctrineTypeMapping[$dbType];
    182▕     }
    183▕     public function hasDoctrineTypeMappingFor($dbType)

      [2m+3 vendor frames [22m
  4   phar:/Applications/Invoker.app/Contents/Resources/invoker.phar/src/Factories/AttributeCollection.php:35
      _HumbugBox7091da86deae\Doctrine\DBAL\Schema\AbstractSchemaManager::listTableColumns("posts")

  5   phar:/Applications/Invoker.app/Contents/Resources/invoker.phar/src/Factories/AttributeCollection.php:15
      _HumbugBox7091da86deae\Invoker\Factories\AttributeCollection::getColumns("App\Models\Post")
```

**Comment by Cazzar** [comment]
Possibly having a larger scope of this, where supporting custom type mappings, similar to how barryvdh/laravel-ide-helper#332 mentions `custom_db_types` as a way of mapping to Doctrine.

Otherwise, is this exposed in the Plugin APIs that we can add our own type mappings?

**Comment by modstore** [comment]
+1

**Comment by mpociot** [comment]
@Cazzar It's currently not possible to update this yourself.
I added JSONB support in the upcoming version though :)

**Comment by Cazzar** [comment]
@mpociot while JSONB is nice and all, the reason I suggested adding custom mappings is in one of the places I would like to use Invoker, I cannot as we have some custom PostgresSQL types which ultimately can map to in my case a string.

If you would like I can create a separate issue for this feature.
