### ISSUE TITLE
Uncaught Error: Call to undefined method Illuminate\Container\Container::version()

### ISSUE THREAD

**Issue by PWParsons** [beyondcode/invoker-community#48]
The following error occurs when opening a local project.

------
**OS**: darwin
**Invoker Version**: 2.0.1
**PHP Binary**: /usr/local/bin/php (8.0.1)
**Laravel Version**: 8.26.1
**Route**: /home

**Error**:
```
Fatal error: Uncaught Error: Call to undefined method Illuminate\Container\Container::version() in phar:///Applications/Invoker.app/Contents/Resources/invoker.phar/vendor/illuminate/support/helpers.php:265
Stack trace:
#0 /Users/peter/code/site/bootstrap/app.php(3): env('APP_ENV')
#1 phar:///Applications/Invoker.app/Contents/Resources/invoker.phar/invoker.php(8): require_once('/Users/peter/Co...')
#2 /Applications/Invoker.app/Contents/Resources/invoker.phar(12): require('phar:///Applica...')
#3 {main}
  thrown in phar:///Applications/Invoker.app/Contents/Resources/invoker.phar/vendor/illuminate/support/helpers.php on line 265
```

Here is a screenshot of the devtools:

![Screenshot 2021-02-02 at 18 17 21](https://user-images.githubusercontent.com/31288220/106628893-eeb62380-6582-11eb-9484-16320552963a.png)

**Comment by mpociot** [comment]
Did you modify your `bootstrap/app.php` file in your project?
I'm calling `app()->version()` which should always work in Laravel

**Comment by PWParsons** [comment]
Hi @mpociot. I forgot about the code I added in `app.php` 🙈. Sorted, thanks!
