### ISSUE TITLE
Doctrine Dbal Compatibility

### ISSUE THREAD

**Issue by AndreSchwarzer** [beyondcode/invoker-community#5]
# Description

I get a doctrine error when I click on a Model in Invoker. All the models and directories containing models are loaded. Just when I click on a specific model to see the "Table View" I get this error.

I pasted the whole error message below.

One thing that my relatively plain Laravel 8 installation differs from an out-of-the box installation, is the usage of no auto incrementing id but an uuid set by an observer on creating.

```php
<?php

namespace App\Observers;

use App\Models\User;
use Illuminate\Support\Str;

class UserObserver
{
    public function creating(User $user): void
    {
        $user->id = (string) Str::uuid();
    }
}
```

The whole construct is just working fine. Also with Tinkerwell https://tinkerwell.app/shares/AndreSchwarzer/b0f4d39f-eb8d-4fd1-9873-cae2d0912590

Please correct me if I am doing something wrong.

# The Error

```
Symfony\Component\ErrorHandler\Error\FatalError 

  Declaration of Doctrine\DBAL\Driver\PDOConnection::prepare($sql, $driverOptions = []) must be compatible with Doctrine\DBAL\Driver\Connection::prepare(string $sql): Doctrine\DBAL\Driver\Statement

  at phar:/Applications/Invoker.app/Contents/Resources/invoker.phar/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:40
     36▕     public function getServerVersion()
     37▕     {
     38▕         return \PDO::getAttribute(\PDO::ATTR_SERVER_VERSION);
     39▕     }
  ➜  40▕     public function prepare($sql, $driverOptions = [])
     41▕     {
     42▕         try {
     43▕             $statement = parent::prepare($sql, $driverOptions);
     44▕             \assert($statement instanceof \PDOStatement);


   Whoops\Exception\ErrorException 

  Declaration of Doctrine\DBAL\Driver\PDOConnection::prepare($sql, $driverOptions = []) must be compatible with Doctrine\DBAL\Driver\Connection::prepare(string $sql): Doctrine\DBAL\Driver\Statement

  at phar:/Applications/Invoker.app/Contents/Resources/invoker.phar/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:40
     36▕     public function getServerVersion()
     37▕     {
     38▕         return \PDO::getAttribute(\PDO::ATTR_SERVER_VERSION);
     39▕     }
  ➜  40▕     public function prepare($sql, $driverOptions = [])
     41▕     {
     42▕         try {
     43▕             $statement = parent::prepare($sql, $driverOptions);
     44▕             \assert($statement instanceof \PDOStatement);

      [2m+1 vendor frames [22m
  2   [internal]:0
      Whoops\Run::handleShutdown()
```

<img width="524" alt="Error Message" src="https://user-images.githubusercontent.com/6991100/105094923-434aa080-5aa5-11eb-80e9-0dc03dddfe04.png">

# Further Details

## Used Software versions

- PHP: (Homebrew) 8.0.1 {binary is linked and loaded through invoker settings}
- Laravel: 8.23.1

## Installed composer packages an their version

- asm89/stack-cors                     v2.0.2
- brick/math                           0.9.1
- composer/package-versions-deprecated 1.11.99.1
- composer/semver                      3.2.4
- composer/xdebug-handler              1.4.5
- dnoegel/php-xdg-base-dir             v0.1.1
- doctrine/annotations                 1.11.1
- doctrine/cache                       1.10.2
- doctrine/dbal                        3.0.0
- doctrine/event-manager               1.1.1
- doctrine/inflector                   2.0.3
- doctrine/instantiator                1.4.0
- doctrine/lexer                       1.2.1
- dragonmantank/cron-expression        v3.1.0
- egulias/email-validator              2.1.2
- facade/flare-client-php              1.3.7
- facade/ignition                      2.5.8
- facade/ignition-contracts            1.0.2
- fakerphp/faker                       v1.13.0
- fideloper/proxy                      4.4.1
- filp/whoops                          2.9.1
- friendsofphp/php-cs-fixer            v2.18.0
- fruitcake/laravel-cors               v2.0.3
- graham-campbell/result-type          v1.0.1
- guzzlehttp/guzzle                    7.2.0
- guzzlehttp/promises                  1.4.0
- guzzlehttp/psr7                      1.7.0
- hamcrest/hamcrest-php                v2.0.1
- laravel/framework                    v8.23.1
- laravel/sail                         v1.2.0
- laravel/tinker                       v2.5.0
- league/commonmark                    1.5.7
- league/flysystem                     1.1.3
- league/mime-type-detection           1.7.0
- mockery/mockery                      1.4.2
- monolog/monolog                      2.2.0
- myclabs/deep-copy                    1.10.2
- nesbot/carbon                        2.43.0
- nikic/php-parser                     v4.10.4
- nunomaduro/collision                 v5.2.0
- opis/closure                         3.6.1
- phar-io/manifest                     2.0.1
- phar-io/version                      3.0.4
- php-cs-fixer/diff                    v1.3.1
- phpdocumentor/reflection-common      2.2.0
- phpdocumentor/reflection-docblock    5.2.2
- phpdocumentor/type-resolver          1.4.0
- phpoption/phpoption                  1.7.5
- phpspec/prophecy                     1.12.2
- phpunit/php-code-coverage            9.2.5
- phpunit/php-file-iterator            3.0.5
- phpunit/php-invoker                  3.1.1
- phpunit/php-text-template            2.0.4
- phpunit/php-timer                    5.0.3
- phpunit/phpunit                      9.5.1
- psr/container                        1.0.0
- psr/event-dispatcher                 1.0.0
- psr/http-client                      1.0.1
- psr/http-message                     1.0.1
- psr/log                              1.1.3
- psr/simple-cache                     1.0.1
- psy/psysh                            v0.10.6
- ralouphie/getallheaders              3.0.3
- ramsey/collection                    1.1.1
- ramsey/uuid                          4.1.1
- roave/security-advisories            dev-latest fe0752a
- schwarzer/php-code-style             1.0.5
- sebastian/cli-parser                 1.0.1
- sebastian/code-unit                  1.0.8
- sebastian/code-unit-reverse-lookup   2.0.3
- sebastian/comparator                 4.0.6
- sebastian/complexity                 2.0.2
- sebastian/diff                       4.0.4
- sebastian/environment                5.1.3
- sebastian/exporter                   4.0.3
- sebastian/global-state               5.0.2
- sebastian/lines-of-code              1.0.3
- sebastian/object-enumerator          4.0.4
- sebastian/object-reflector           2.0.4
- sebastian/recursion-context          4.0.4
- sebastian/resource-operations        3.0.3
- sebastian/type                       2.3.1
- sebastian/version                    3.0.2
- swiftmailer/swiftmailer              v6.2.5
- symfony/console                      v5.2.1
- symfony/css-selector                 v5.2.1
- symfony/deprecation-contracts        v2.2.0
- symfony/error-handler                v5.2.1
- symfony/event-dispatcher             v5.2.1
- symfony/event-dispatcher-contracts   v2.2.0
- symfony/filesystem                   v5.2.1
- symfony/finder                       v5.2.1
- symfony/http-client-contracts        v2.3.1
- symfony/http-foundation              v5.2.1
- symfony/http-kernel                  v5.2.1
- symfony/mime                         v5.2.1
- symfony/options-resolver             v5.2.1
- symfony/polyfill-ctype               v1.22.0
- symfony/polyfill-iconv               v1.22.0
- symfony/polyfill-intl-grapheme       v1.22.0
- symfony/polyfill-intl-idn            v1.22.0
- symfony/polyfill-intl-normalizer     v1.22.0
- symfony/polyfill-mbstring            v1.22.0
- symfony/polyfill-php70               v1.20.0
- symfony/polyfill-php72               v1.22.0
- symfony/polyfill-php73               v1.22.0
- symfony/polyfill-php80               v1.22.0
- symfony/process                      v5.2.1
- symfony/routing                      v5.2.1
- symfony/service-contracts            v2.2.0
- symfony/stopwatch                    v5.2.1
- symfony/string                       v5.2.1
- symfony/translation                  v5.2.1
- symfony/translation-contracts        v2.3.0
- symfony/var-dumper                   v5.2.1
- theseer/tokenizer                    1.2.0
- tijsverkoyen/css-to-inline-styles    2.2.3
- vlucas/phpdotenv                     v5.2.0
- voku/portable-ascii                  1.5.6
- webmozart/assert                     1.9.1

***edit:*** Typo

**Comment by mpociot** [comment]
Hi Andre,

thank you for the very detailed bug report. One important information is missing: Which Invoker version did you use? :)

**Comment by AndreSchwarzer** [comment]
> Hi Andre,
> 
> thank you for the very detailed bug report. One important information is missing: Which Invoker version did you use? :)

Sorry 😅 `Version 2.0.0-RC10`

But I think we can close this now. I Updated to `Version 2.0.0-RC13`. **Everything works now.**

<img width="848" alt="Screen Shot 2021-01-20 at 10 01 52 PM" src="https://user-images.githubusercontent.com/6991100/105234246-40b27e80-5b6b-11eb-9169-f3d0fbf249c1.png">
