### ISSUE TITLE
[bug] Error with no error when opening a project

### ISSUE THREAD

**Issue by oniice** [beyondcode/invoker-community#50]
I get the following error, when opening a `Laravel 7.28.1` project.
I do not have `/home` route in the project.
         
------
**OS**: darwin
**Invoker Version**: 2.0.1
**PHP Binary**: /usr/local/bin/php
**Route**: /home

**Error**:
```

```

**Comment by oniice** [comment]
Same as #33

**Comment by mpociot** [comment]
I'll close this and follow up in #33 👍
