### ISSUE TITLE
Add an ability to select connection

### ISSUE THREAD

**Issue by MasterRO94** [beyondcode/invoker-community#51]
I have multiple database connections configured in my app and the biggest part of models cannot be open and throughs an Exception `SQLSTATE[42S02]: Base table or view not found` as they are using non-default connection that is specified on the fly.

It would be great if Invoker check connections config and allow to choose one. Something like this
![image](https://api.monosnap.com/file/download?id=GQsrBFRfIzWEeWmJgEu6V61XOSj1bu)

**Comment by mechelon** [comment]
We added the possibility to pre-load code per project in 2.10.0. This code gets evaluated before Invoker does it's thing, so you can use it to override configuration values, modify connections etc.

**Comment by MasterRO94** [comment]
What if I have multiple connections, how I can switch between them using preloading? I see the only way is to change preload code every time and reload the project.
