### ISSUE TITLE
Error when returning to remote project  when --includeVendor=true

### ISSUE THREAD

**Issue by bomshteyn** [beyondcode/invoker-community#52]
------
**OS**: darwin
**Invoker Version**: 2.0.1
**PHP Binary**: /usr/local/bin/php
**Route**: /home

**Error**:
```
PHP Fatal error:  Trait 'GuzzleHttp\Stream\StreamDecoratorTrait' not found in /home/forge/app.labelnship.com/vendor/aws/aws-sdk-php/src/Handler/GuzzleV5/PsrStream.php on line 13
```

FlareApp Share: https://flareapp.io/share/xPQ6nkX7#F1

**Comment by mpociot** [comment]
This error occurs by Invoker scanning your classes and basically means that you have an issue in this class. From the error, it seems like the Guzzle dependency is missing?

I found this: https://github.com/aws/aws-sdk-php/issues/1437

Anyway, this is not an issue in Invoker, but it's in your codebase
