### ISSUE TITLE
[bug][osx] empty error message when your (legacy) code does have php syntax errors (with solution)

### ISSUE THREAD

**Issue by Gompje** [beyondcode/invoker-community#53]
read more about my journey at #28
I'm making this issue again to document and help others

relevant journey:
- legacy code contained php errors (upgraded 5y old project)
- displayed an error when connecting to the branch locally, but not the error message (I was lost)
- error again when ssh connecting (same branch) but now I did have an error message: saw it was php related 😅 
- run inspection on the whole project, fixed them (phpstorm → code → inspection //use a filter!)
- works 🎉

**Comment by mpociot** [comment]
I don't think this is something that we can fix in Invoker. The PHP code needs to be scanned in order to detect possible models, events, jobs, etc.
If those classes contain syntax errors, Invoker won't load those files.
