### ISSUE TITLE
[feature request] ability to hide some models in the UI

### ISSUE THREAD

**Issue by Gompje** [beyondcode/invoker-community#54]
I have a multi-tenant app. Some models are for the tenants only and use specific connection settings for them to run. 
I do not need to see those models, I even don't want to be able to! :)

For me a solution would be to simple be able to hide some models. Favo would work too. 🤔   or is this already possible?

**Comment by mpociot** [comment]
How would you like to hide them? Configure it in the UI, or in your codebase (for example a docblock added to the model classes).

**Comment by mechelon** [comment]
Duplicate of #100
