### ISSUE TITLE
[Feature request] Group / folder structure for projects

### ISSUE THREAD

**Issue by johanmolen** [beyondcode/invoker-community#55]
Make it possible to structure projects on the home screen with folders, groups, colors or a combination of those. That way we can, for example, easily separate production, staging and development projects.

**Comment by ndeblauw** [comment]
Thinking this a bit further into implementation: basically these are two fields to add, at the level of label: a tag (group, project) and a colour. And then in the index view (start screen): allow the view to be sorted (based on label and/or tag) and to be grouped (based on tag). 

The colour coding is additional. And could benefit from allowing us to "name the colour" (e.g. as in Trello, with labels), but that is (imho) not needed at all.

**Comment by johanmolen** [comment]
@ndeblauw thanks for the nice addon 😁

**Comment by pxlrbt** [comment]
+1: Labelling for Production/Staging environments would be really helpful to not mess something up.
Further improvement could be to color the status bar or something else in the labels color or when on production.

**Comment by mechelon** [comment]
A combination of all your suggestions will be available in the next release. :)
