### ISSUE TITLE
Can't connect to any remote sites via Forge API key

### ISSUE THREAD

**Issue by arvesolland** [beyondcode/invoker-community#57]
------
**OS**: darwin
**Invoker Version**: 2.0.1
**PHP Binary**: /usr/local/bin/php
**Route**: /home

**Error**:
```
fatal: not a git repository (or any of the parent directories): .git
```

**Comment by mpociot** [comment]
Could you please post a screenshot of your devtools? You can access them through the "Developer" main menu.

**Comment by HapLifeMan** [comment]
Same problem here even if the Forge API key is saved, requests are OK when clicking on "Update sites and servers" but nothing is displayed on the dashboard, even if I reload the app.
![CleanShot 2021-02-03 at 16 06 04](https://user-images.githubusercontent.com/1854141/106766166-e10fa500-6639-11eb-9fe4-5e29501af180.png)

**Comment by tfevens** [comment]
FWIW, I just attempted this on Win 10, v2.0.2, and was able to connect to Forge without issue.  All of my servers & sites were loaded,

**Comment by arvesolland** [comment]
![Screen Shot 2021-02-04 at 5 07 46 pm](https://user-images.githubusercontent.com/2617224/106857306-978f8a80-670b-11eb-9b18-bde66f77463a.png)


![Screen Shot 2021-02-04 at 5 07 46 pm](https://user-images.githubusercontent.com/2617224/106857346-a9712d80-670b-11eb-96d9-9bfaf9652b40.png)

**Comment by mpociot** [comment]
@arvesolland Could you try and fix the error regarding your `ArveSegment` class and see if that helps?

**Comment by HapLifeMan** [comment]
Hey, any update on this? I bought a perpetual license and the app is not usable for me, thanks.

**Comment by mpociot** [comment]
Do you get an error in your developer tools? I don't think it's related to the error that @arvesolland mentioned.

**Comment by HapLifeMan** [comment]
I don't have any error, I tried to switch between tabs and refresh forge servers and sites:
<img width="1193" alt="Capture d’écran 2021-02-09 à 13 49 03" src="https://user-images.githubusercontent.com/1854141/107365838-a2686780-6add-11eb-9435-e7374fa8494f.png">

**Comment by mpociot** [comment]
Could you please take a look at the network requests when you save the forge key/refresh sites?
It should give you a JSON with all of your sites and servers. 
If you want, you can also get in touch with me via Telegram so that I can help you debug and fix this (@mpociot)
