### ISSUE TITLE
Unknown database type json requested

### ISSUE THREAD

**Issue by vmitchell85** [beyondcode/invoker-community#6]
Invoker Version: 2.0.0-RC16
Laravel Version: 6.20.14

I got the following error when attempting to view my Users.

This application does have a custom trait that makes use of a custom package we built.

I have a feeling it might be due to us using [`staudenmeir/eloquent-json-relations`](https://github.com/staudenmeir/eloquent-json-relations)

There are a number of models that we use in the package namespace, is it possible to pull those models in as well?

Unfortunately I can't share too many details of the package publicly here on GitHub.

Thanks in advance!

```
_HumbugBox5c39106fa180\Doctrine\DBAL\Exception  : Unknown database type json requested, _HumbugBox5c39106fa180\Doctrine\DBAL\Platforms\MySqlPlatform may not support it.

  at phar:///tmp/invoker.phar/vendor/doctrine/dbal/lib/Doctrine/DBAL/Platforms/AbstractPlatform.php:179
    175|             $this->initializeAllDoctrineTypeMappings();
    176|         }
    177|         $dbType = \strtolower($dbType);
    178|         if (!isset($this->doctrineTypeMapping[$dbType])) {
  > 179|             throw new \_HumbugBox5c39106fa180\Doctrine\DBAL\Exception('Unknown database type ' . $dbType . ' requested, ' . static::class . ' may not support it.');
    180|         }
    181|         return $this->doctrineTypeMapping[$dbType];
    182|     }
    183|     public function hasDoctrineTypeMappingFor($dbType)

  Exception trace:

  1   _HumbugBox5c39106fa180\Doctrine\DBAL\Platforms\AbstractPlatform::getDoctrineTypeMapping()
      phar:///tmp/invoker.phar/vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/MySqlSchemaManager.php:71

  2   _HumbugBox5c39106fa180\Doctrine\DBAL\Schema\MySqlSchemaManager::_getPortableTableColumnDefinition()
      phar:///tmp/invoker.phar/vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/AbstractSchemaManager.php:345

  Please use the argument -v to see more details.
  ```

**Comment by mpociot** [comment]
You should be able to fix this, by specifying the MySQL server version in Laravel - see https://github.com/laravel/framework/issues/15772#issuecomment-685945057

**Comment by vmitchell85** [comment]
That got my User model working, thanks! I'll start adding the version in my projects.

Any way to add Models from packages?

**Comment by vmitchell85** [comment]
Going to close this issue since the User model is fixed
