### ISSUE TITLE
Improve the "connect with SSH" screen

### ISSUE THREAD

**Issue by ndeblauw** [beyondcode/invoker-community#65]
- Please don't let label (and host) overwrite the host field and project path. It's fine that you use them for the initial suggestion for project path, but once I wrote something there, it's annoying to see a label change mess things up.
   - As a use case: I have several sites on one server. When labeling, I like to start with the server name and add then the site reference. As host, I use the ip address. And both are not related to the project path.

- Imho, you could better structure the form a bit differently. Yes, it will become larger, but also more logical. My suggestion is to have the following subsections
  - Label  -> is purely for invoker reference
  - Host + project path + binary path -> is server to connect to (and locations on it)
  - Username+password & private key + passphrase
- If would be nice if the passphrase is not displayed openly (after filling it out)
- Small feature request: at the level of label, allow us to pick a color. It's so nice to be able to color code (groups of) servers/sites, which makes it faster to retrieve them later [see also #55 ]

**Comment by mechelon** [comment]
Groups and labels will come in the next release & should cover some of your suggestions.
The behaviour of the passphrase/password visibility will also be fixed.

If you still see room for improvement after the release, feel free to reopen this issue. 🙂
