### ISSUE TITLE
Saving doesn't seem to do anything

### ISSUE THREAD

**Issue by gavinhewitt** [beyondcode/invoker-community#69]
Or at least, not on my machine.

Also, there's 2 things that I personally find a bit strange:

1) Clicking the save button in a modal doesn't close it. You have to explicitly scroll up to use the X.

2) The save button is white (on the bigger modals)

![image](https://user-images.githubusercontent.com/1969103/106782010-fc82ac00-6649-11eb-814d-7812cec8a577.png)

**Comment by mpociot** [comment]
Hi!

Could you please open the dev tools (you can open them from the "Developer" main menu) and tell me if there are any errors? Maybe you can upload a screenshot - that would help finding what's causing the issue

**Comment by io238** [comment]
Got the same issue. Following error is showing when trying to update a model.

![image](https://user-images.githubusercontent.com/26689138/106956518-fe766900-6736-11eb-8a7e-ac89cd248174.png)

**Comment by gavinhewitt** [comment]
Ah yeah, there's loads of errors. Haven't looked into them in detail but most likely something wrong at my end.

Will report back if I'm not able to fix it.

Not closing it because of @io238 's issue.

**Comment by mpociot** [comment]
Yeah, I will take care of hiding the plugin error, as it's really just a verbose log and doesn't break anything.
The main issue must be in the actual update process.

If you can't open anything, could you try turning off scanning for vendor folders?
Startup/project loading errors usually occur because Invoker scans your project for potential models/mails and then detects errors in your code.

**Comment by gavinhewitt** [comment]
I think I've figured it out, though I'm not sure if this error was explicitly showing yesterday.

For some reason on my machine I'm always having troubles with some lib not being loaded, or the wrong one being loaded, so I have to fix it with `brew switch icu4c 67.1` (or 66.1).

Console showed me that the wrong lib was loaded, switched it and then invoker started working. Next time when I encounter an invoker issue I'll check more thoroughly. Sorry for the noise. This can be closed.

However, I still find it confusing that the Save button is white and looks like an input, but that may be just me ;-)

**Comment by mpociot** [comment]
I also just published version 2.1.0 which fixes an error that could occur when specific column types (such as JSON) are not defined. I'll close this for now :)
