### ISSUE TITLE
Model Class Names and Model Folders clash and aren't displayed

### ISSUE THREAD

**Issue by colinmackinlay** [beyondcode/invoker-community#76]
Invoker seems to get confused if the Models folder contains a filename and a folder with the same name. I have two such "clashes". One is called "Application" and another is "Enrolment". Both exist in the top of the Models folder and both have corresponding folders (with additional model classes that they use). For one of them I can see the top-level model in Invoker but not the folder. For the other one it is the other way round.

I think this is a "bug". I expect I can work around this my moving the top-level models into the folders (and was thinking of doing this anyway) but it seems something worth checking is reproducible.

**Comment by mpociot** [comment]
Could you show me a screenshot of the folder/namespace structure that you have locally vs. the one you see in Invoker?
I tried to replicate the issue, but it works with my structure - so I guess I'm not doing it right :)

![image](https://user-images.githubusercontent.com/804684/106867191-98093080-66cd-11eb-8e6f-3acb27414ffe.png)

**Comment by colinmackinlay** [comment]
Local structure
![Local](https://user-images.githubusercontent.com/7833362/106868295-85d7c400-66c6-11eb-829c-824e739f49fa.PNG)
Invoker
![Invoker](https://user-images.githubusercontent.com/7833362/106868329-8f612c00-66c6-11eb-9dfc-25e0ed1a9726.PNG)

Same thing on both local and remote :(

I've stripped the missing Enrolment class down to bare bones to find what causes the issue:
```
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Http\RedirectResponse;
use Illuminate\Notifications\Notifiable;
use Illuminate\Routing\Redirector;


class Enrolment extends Authenticatable implements MustVerifyEmail {

    use HasFactory, Notifiable, SoftDeletes;

    public function impersonate() : Redirector|RedirectResponse
    {

    }

}
```
If I remove `Redirector` or `RedirectResponse` as the function return type then it appears as it should but if both are present it fails to appear in Invoker
![Capture](https://user-images.githubusercontent.com/7833362/106879138-ac036100-66d2-11eb-85d2-f23eb4b88f3d.PNG)

This is very strange as the Application class has the same function and return type in it. It doesn't have a subfolder in Models though. Putting an Application folder in doesn't cause a problem and nor does including any classes in there and in that namespace.

Removing the Enrolment folder and it's classes also doesn't enable Invoker to see the stripped down Enrolment class. But again, as soon as I remove either `Redirector` or `RedirectResponse` Invoker is fine with it.

I've also stripped the Application class right down to mirror Enrolment apart from the class name but there is no problem.

SO I've ruled out this being to do with subfolder names I think.

At this stage I have a workaround in terms of not using that return type. As you've set up a blank test project perhaps you could just try that skeleton code in both Application and Enrolment as a quick check of reproducibility? - I will too. If it doesn't reproduce then probably best to just close the issue

**Comment by colinmackinlay** [comment]
This is not reproducible in a fresh Laravel project so I'll close the issue.

There must be something in my main project that upsets Invoker. I'll continue trying to isolate and if I can find something specific will open a new issue. Thank you for looking at it.
