### ISSUE TITLE
Mails viewable but not if delivered by notifications

### ISSUE THREAD

**Issue by colinmackinlay** [beyondcode/invoker-community#77]
My Mails are all delivered using Notifications - I presume that is why I can't see any Mails. It would be nice if Mailables rendered by Notifications could be shown by Invoker!

**Comment by mpociot** [comment]
Yeah, I actually think this should be a separate feature that lists notifications in general and allows you to send/preview them with their available channels.

**Comment by mpociot** [comment]
I started working on this feature yesterday. You will be able to preview all of your notifications, as well as send them to any available notifiable models

![image](https://user-images.githubusercontent.com/804684/107207172-4845a480-6a00-11eb-93c1-ae3b497a1ec9.png)

**Comment by mpociot** [comment]
This is already released 🎉
