### ISSUE TITLE
Windows path to PHP broken when also using linux path as default

### ISSUE THREAD

**Issue by colinmackinlay** [beyondcode/invoker-community#78]
I am a Windows user for development although I deploy on linux. The default path to PHP works fine for my remote (Forge/Invoker) deployments but of course not for Windows. 

If I set the correct path to php in the local project in Invoker (available as a setting before I've ever attempted to connect) it still doesn't work - I've copied the debug information below and that shows that Invoker didn't use my provided path to PHP `C:\laragon\bin\php\php-8.0.1-Win32-vs16-x64\php.exe`

Worse, because Invoker has attempted to connect to the project, I can't now access the settings from the launch page and can only delete the project. When I add it back, Invoker remembers it and I don't get the option to change the settings and can only attempt to connect (which fails) or I can delete again.

```
**OS**: win32
**Invoker Version**: 2.0.1
**PHP Binary**: /usr/local/bin/php
**Route**: /home?project=889346
**Error**:

Error: spawn /usr/local/bin/php ENOENT
```

**Comment by mpociot** [comment]
Are you using a local, or a remote project?
You should configure your local PHP binary in the global invoker settings. When configuring an SSH connection, you can manually change the location to the `php` binary - but setting it to the default should be good enough.

**Comment by colinmackinlay** [comment]
Thanks - perfect. As long as the global setting is the local one the remote can be changed and works.
