### ISSUE TITLE
[Feature Request] Allow specifying other Model paths

### ISSUE THREAD

**Issue by vmitchell85** [beyondcode/invoker-community#8]
I'm not sure how Invoker pulls the models but I have a package that adds a bunch of it's own Models,

They all extend `Illuminate\Database\Eloquent\Model`, and are namespaced.

**Comment by mpociot** [comment]
This just landed in the latest release candidate and can be activated in the global settings.
It is turned off by default, as it can increase the time it takes to open a project:

![image](https://user-images.githubusercontent.com/804684/106047156-87602580-60e3-11eb-9ccb-b44f846b94ad.png)

Classes will appear in their namespaces as you would expect them to:

![image](https://user-images.githubusercontent.com/804684/106047205-9941c880-60e3-11eb-84d6-1441fd0a638c.png)

**Comment by vmitchell85** [comment]
@mpociot... how do you do these things so fast!!! Thanks a ton!

Would it be possible to turn it on and off per project, or is that too much work?

**Comment by mpociot** [comment]
We want to move the persisted settings and vendor folder settings into project-specific settings, but this won't happen until we release 2.1, as it would require some more work. But I agree, it makes sense on a project level.

**Comment by vmitchell85** [comment]
Thanks again! Excited to see new features come!
