### ISSUE TITLE
Throwing errors when trying to open a local project

### ISSUE THREAD

**Issue by timrspratt** [beyondcode/invoker-community#81]
Not sure how to provide more information other than the error that keeps popping up when loading the project. This happened since upgrading, I then opened another project (which was Laravel 6 and failed to open). From then on the project I had previously opened with success now fails on opening with the following error            
------
**OS**: darwin
**Invoker Version**: 2.0.2
**Laravel Version**: 8.26.1
**Local project**: true
**PHP Binary**: /usr/local/bin/php
**Route**: /home

**Error**:
```
Symfony\Component\ErrorHandler\Error\FatalError 

  Trait 'GuzzleHttp\Stream\StreamDecoratorTrait' not found

  at /Users/tim/code/anvil/vendor/aws/aws-sdk-php/src/Handler/GuzzleV5/PsrStream.php:13
      9▕  * Adapts a Guzzle 5 Stream to a PSR-7 Stream.
     10▕  *
     11▕  * @codeCoverageIgnore
     12▕  */
  ➜  13▕ class PsrStream implements Psr7StreamInterface
     14▕ {
     15▕     use StreamDecoratorTrait;
     16▕ 
     17▕     /** @var GuzzleStreamInterface */


   Whoops\Exception\ErrorException 

  Trait 'GuzzleHttp\Stream\StreamDecoratorTrait' not found

  at /Users/tim/code/anvil/vendor/aws/aws-sdk-php/src/Handler/GuzzleV5/PsrStream.php:13
      9▕  * Adapts a Guzzle 5 Stream to a PSR-7 Stream.
     10▕  *
     11▕  * @codeCoverageIgnore
     12▕  */
  ➜  13▕ class PsrStream implements Psr7StreamInterface
     14▕ {
     15▕     use StreamDecoratorTrait;
     16▕ 
     17▕     /** @var GuzzleStreamInterface */

      [2m+1 vendor frames [22m
  2   [internal]:0
      Whoops\Run::handleShutdown()
```

**Comment by timrspratt** [comment]
More info: I've since turned off the "Include vendor folders" and it is loading, so I presume there is an issue when this feature is enabled?

**Comment by tfevens** [comment]
I'm guessing there's a conflict between Guzzle versions.  This package wants to use v5 but I believe Laravel is pulling in v6.  Perhaps the namespace has changed or something similar, but the Trait 'GuzzleHttp\Stream\StreamDecoratorTrait' can't be found.  I'm guessing you don't see this error when running the app in a browser?

**Comment by mpociot** [comment]
The "include vendor folders" option is basically reflecting/loading all of the classes from your composer.json "require" section.
If any of these classes throw an error, it will be shown - as some of these, unfortunately, can not be caught.
I can blacklist certain packages that won't contain Laravel packages though, so maybe this could be a workaround
