### ISSUE TITLE
Two Vertical Scrollbars When > 18 Models in View

### ISSUE THREAD

**Issue by tfevens** [beyondcode/invoker-community#82]
When the Model view table contains more than 18 models, there are two vertical scrollbars presented.

As the table expands farther down, that "frame" seems to have a max-height set, causing the scrollbar inside to appear.

![ModelTable](https://user-images.githubusercontent.com/701763/106812776-7dd83f80-6646-11eb-8241-cc58285a6ab9.png)

This is especially annoying as you have to scroll the inside table, then 'move' to be able to scroll down to get to the pagination.

Perhaps related, as the results/filters/pagination footer expands slightly below the "height" of the Invoker window, the outside scrollbar is present as well, when there are more than 10 rows in the table.

![ModelTable2](https://user-images.githubusercontent.com/701763/106813673-b2003000-6647-11eb-8282-793d6300ed51.png)

Perhaps, the footer could be fixed to the bottom of the Invoker window, regardless of size. This would prevent the outer scrollbar from appearing, and leaving only the table to cause scrolling in the app.

------
**OS**: win32 (Win 10)
**Invoker Version**: 2.0.2
**Laravel Version**: 8.25.0

**Comment by timrspratt** [comment]
I get this on mac too, it always seems like the parent scrollbar is just a tad too small, as if it's padding/margin affecting it?

**Comment by sschlein** [comment]
This one is definitely on the short term bug fix list, it's bugging me for weeks but other things have been more important until now.

**Comment by mechelon** [comment]
Will be fixed in the next version.
