### ISSUE TITLE
Reload Models List After make:model

### ISSUE THREAD

**Issue by tfevens** [beyondcode/invoker-community#88]
Currently, the model list is cached when initially connecting with Invoker.  If a new model is then made (via the commands menu or externally), that new model doesn't appear until you reconnect to the project.

Could an option be added to "refresh" the model list, perhaps a right-click content menu, or some other means that could refresh the list without having to reconnect?

**Comment by mpociot** [comment]
Yeah good idea. Maybe a refresh button next to the "Models" headline in the sidebar with all the model namespaces

**Comment by mpociot** [comment]
I just added this. It will available with the next release

![image](https://user-images.githubusercontent.com/804684/107206994-0ddc0780-6a00-11eb-9be0-bb92f960f35a.png)
