### ISSUE TITLE
Allow for organizing commands by group/prefix.

### ISSUE THREAD

**Issue by corsair** [beyondcode/invoker-community#89]
When utilizing popular Laravel libraries/services such as Nova, Horizon, and Telescope, it can quickly become very difficult to navigate through the Commands list due to the sheer amount of commands. As an application grows, this can become harder to manage.

Would there be any consideration to allowing for "grouping" commands together? This could be accomplished by automatically detecting groups based on their prefix (ie: ``horizon:``work) or otherwise allow for the creation of groups within the project.
![image](https://user-images.githubusercontent.com/1847891/107143192-8cde1c80-68e8-11eb-85bb-6e35cebcc391.png)

**Comment by mpociot** [comment]
Great idea. This will be in the next release 
![image](https://user-images.githubusercontent.com/804684/107206894-ef760c00-69ff-11eb-96a3-0eff10bd90b8.png)
