### ISSUE TITLE
Sending Mailables

### ISSUE THREAD

**Issue by corsair** [beyondcode/invoker-community#90]
Would there be any consideration for allowing for the sending of a Mailable in addition to previewing?

Given that Invoker can access the environmental variables of a project whether local or remote, it should be able to determine the configuration of variables such as ``MAIL_DRIVER``, ``MAIL_HOST``, and so forth and be able to utilize such for sending out a Mailable once the provided values have been validated.

**Comment by mpociot** [comment]
This will be available in the next version!

**Comment by corsair** [comment]
@mpociot You (and the BeyondCode team) rock, thank you!
