### ISSUE TITLE
Disable "required field" check for a specific model

### ISSUE THREAD

**Issue by schmidfelix** [beyondcode/invoker-community#91]
When trying to create a new model which has a required field which get's filled by a model listener, the creation fails and Invoker says: "The preview secret field is required".

Is there any option to disable that check or Invoker to detect which fields get filled by a listener?

My code:
```php
static::creating(function (Post $post) {
    $post->preview_secret = Str::random(10);
});
```

**Comment by mpociot** [comment]
Hi Felix,

disabling the checks is currently not possible, but I thought about maybe removing them completely. I mean we show PHP errors anyway, so if you save a model and your database does not allow nullable fields, then PHP would show you an error too.

**Comment by mpociot** [comment]
This will be in the next release
