### ISSUE TITLE
Model view not working

### ISSUE THREAD

**Issue by marju212** [beyondcode/invoker-community#95]
------
**OS**: darwin
**Invoker Version**: 2.1.0
**Laravel Version**: 8.9.0
**Local project**: true
**PHP Binary**: /usr/local/bin/php
**Route**: /project/index?class=App%5CModels%5CStore&time=1612811087826&project=local-syog6BNm4ZNpaZtLX97hub

**Error**:
```

```

**Comment by mpociot** [comment]
Could you show me a screenshot from the developer tools? You can open them from the "Developer" main menu.

**Comment by marju212** [comment]
Where can I find the developer tools/Developer menu?

**Comment by marju212** [comment]
There is no exception if I remove the 'point' column from the mysql/model. Point is not supported?

**Comment by jcordingley** [comment]
Hi @mpociot i am experiencing the same issue, is there an area of dev tools you want to see? 

![image](https://user-images.githubusercontent.com/6438453/107501187-07c86100-6b8f-11eb-89bb-af46339324db.png)

**Comment by mpociot** [comment]
Please take a look at the log file here:
`%USERPROFILE%\AppData\Roaming\Invoker\logs\renderer.log`

This is most likely an error due to a syntax issue in your model.

**Comment by jcordingley** [comment]
@mpociot this was an old issue, you fixed it a while back and the error came from our model classes having "_" in them.
