### ISSUE TITLE
Mailables not showing for vendor mails (Jetstream)

### ISSUE THREAD

**Issue by pablius** [beyondcode/invoker-community#96]
I'm using Jetstream 2 as the base for a project, and even if I have the option to "include vendor folder" active, and the Models show. No mails show up.

**Comment by mpociot** [comment]
I started working on a new "Notification" section that will allow you to preview and send any Laravel notification classes from Invoker. I think Jetstream doesn't use Mailables, but Notifications.

https://twitter.com/marcelpociot/status/1358549569118883840

**Comment by pablius** [comment]
Yes! I saw your tweet and it reminded me of this. What you're creating is awesome :)

I just checked the code, and in fact it uses both! You can se a Mailable here: https://github.com/laravel/jetstream/blob/2.x/src/Mail/TeamInvitation.php

**Comment by mpociot** [comment]
Oh right - I also looked at the mailable detection and it was indeed not yet using the vendor setting!

![image](https://user-images.githubusercontent.com/804684/107288479-d010ca80-6a63-11eb-828d-5e0a5eed2199.png)

This will make be available in the next update (probably tomorrow)

**Comment by pablius** [comment]
You re awesome!
