### ISSUE TITLE
Cannot view a model relationship

### ISSUE THREAD

**Issue by cca-bheath** [beyondcode/invoker-community#97]
This happens when I try to open a related model to user from the relationship in the model view.  The UserExtended model doesn't have an ID index but instead uses user_id and perhaps that is the issue.

I can open this model just fine from the tree, but that's not as convenient
            
------
**OS**: linux
**Invoker Version**: 2.1.0
**Laravel Version**: 8.26.1
**Local project**: true
**PHP Binary**: /usr/local/bin/php
**Route**: /project/show?class=App%5CModels%5CUsersExtended&project=local-8TNv2PcFsAhUZAm5RudKZL

**Error**:
```
Error 

  Call to a member function setAppends() on null

  at phar:///tmp/.mount_InvokegrRk12/resources/invoker.phar/src/Actions/ShowResourceAction.php:73
     69▕     }
     70▕     public function addAccessors() : self
     71▕     {
     72▕         if (!isset($this->request->accessors) || !\count($this->request->accessors)) {
  ➜  73▕             $this->entry->setAppends([]);
     74▕             return $this;
     75▕         }
     76▕         $this->entry->setAppends($this->request->accessors);
     77▕         return $this;

  1   phar:///tmp/.mount_InvokegrRk12/resources/invoker.phar/src/Actions/ShowResourceAction.php:24
      _HumbugBox190a6ad96ca4\Invoker\Actions\ShowResourceAction::addAccessors()

  2   phar:///tmp/.mount_InvokegrRk12/resources/invoker.phar/src/ActionInvoker.php:33
      _HumbugBox190a6ad96ca4\Invoker\Actions\ShowResourceAction::execute()
```

![Screenshot_20210208_153742](https://user-images.githubusercontent.com/35047806/107295468-47bf0500-6a24-11eb-9968-6e1117104c10.png)

**Comment by voicecode-bv** [comment]
Same error here while trying to open any relation this way

------
**OS**: darwin
**Invoker Version**: 2.2.0
**Laravel Version**: 8.27.0
**Local project**: unknown
**PHP Binary**: /usr/local/bin/php
**Route**: /project/show?class=App%5CModels%5CSettings&project=remote-9xb6FqdSaT5DwY4saPrues

**Error**:
```
In ShowResourceAction.php line 73:
                                                  
  Call to a member function setAppends() on null
```

**Comment by mpociot** [comment]
This will be fixed in the next version.
