### ISSUE TITLE
[Feature] Trigger Events

### ISSUE THREAD

**Issue by michavie** [beyondcode/invoker-community#98]
Trigger events within and outside the project (packages: e.g. trigger events in Laravel Cashier package, ...) similar to the upcoming notifications feature: https://twitter.com/marcelpociot/status/1358549569118883840/photo/1

**Comment by mpociot** [comment]
Yup, this is coming after the notification feature is out of the door: https://twitter.com/marcelpociot/status/1357081409236656137

You will be able to dispatch jobs and events from the UI
